change all icons on dashboard, change all hover and delete hover green…
LT-Students/DigitalOffice-frontend pull request #138
Opened 2021-07-19 18:31 UTC by AnastassiaVarabei

… and orange in dashboard.components.sccs

2021-07-20 10:58 UTC, tsinevik requested changes

2021-07-20 10:58 UTC, tsinevik commented on src/app/modules/admin/components/dashboard/dashboard.component.html
> +			<div class="section__button section__button_color_purple" (click)="openModalClick.next(modalType.NEW_OFFICE)">
Т.к. у нас теперь все кнопки одним цветом подсвечиваются, то можно убрать класс section__button_color_purple, а псевдокласс :hover добавить к классу section__button

2021-07-20 10:58 UTC, tsinevik commented on src/app/modules/admin/components/dashboard/dashboard.component.scss
>  			}
Вместо всего этого блока можно оставить &:hover

2021-07-20 15:55 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/dashboard/dashboard.component.html
> +			<div class="section__button section__button_color_purple" (click)="openModalClick.next(modalType.NEW_OFFICE)">
Удалила

2021-07-20 15:56 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/dashboard/dashboard.component.scss
>  			}
Оставил только  &:hover

2021-07-21 08:33 UTC, tsinevik approved these changes

2021-07-21 08:34 UTC, merged