Improvement/modal width
LT-Students/DigitalOffice-frontend pull request #147
Opened 2021-07-22 19:01 UTC by Evgenia1394

Added a list with pop-up widths. Changed openModal function - added new argument with width.

2021-07-23 08:08 UTC, tsinevik requested changes
Также тебе нужно обновить ветку develop и смержить её в эту ветку и порешать конфликты. У тебя будет, как минимум, один конфликт в файле Auth.service, надо будет принять приходящие изменения.

2021-07-23 08:08 UTC, tsinevik commented on src/app/modules/admin/components/new-project/new-project.component.ts
> +		const dialogRef = this._modalService.openModal(UserSearchComponent, ModalWidth.L ,modalData);
Пробел перед запятой, а не после. Чтобы не допускать таких вещей, используй форматирование с помощью prettier. Для этого в WebStorm нажми правой кнопкой мыши по коду или по файлу и выбери в конце списка Reformat with Prettier.

2021-07-23 08:08 UTC, tsinevik commented on src/app/modules/admin/components/team-cards/team-card.component.ts
> +		this._modalService.openModal(UserSearchComponent, ModalWidth.M , configData);
Лишний пробел

2021-07-23 08:08 UTC, tsinevik commented on src/app/modules/admin/components/team-cards/team-card.component.ts
> +		const dialogRef = this._modalService.openModal(DeleteDirectionComponent, ModalWidth.M , configData, ModalResult);
и здесь

2021-07-25 19:32 UTC, tsinevik requested changes

2021-07-25 19:32 UTC, tsinevik commented on src/app/core/services/auth.service.ts
> +	public signUp$(createCredentialsRequest: CreateCredentialsRequest): Observable<any> {
В Observable нужно указать конкретный тип

2021-07-25 19:32 UTC, tsinevik commented on src/app/core/services/auth.service.ts
>              switchMap((authResponse: AuthenticationResponse) => this._userService.getUserSetCredentials(authResponse.userId)),
Эти две строки удали

2021-07-25 19:32 UTC, tsinevik commented on src/app/modules/admin/components/dashboard/dashboard.component.ts
> +import { NewRoleComponent } from '../../modals/new-role/new-role.component';
Ты здесь неправильно решила конфликт при слиянии веток, ты приняла приходящие изменения, хотя тут как раз твои нужно было оставить

2021-07-25 19:48 UTC, Evgenia1394 commented on src/app/core/services/auth.service.ts
> +	public signUp$(createCredentialsRequest: CreateCredentialsRequest): Observable<any> {
не могу понять какой теперь тип указывать?

2021-07-26 09:22 UTC, tsinevik approved these changes

2021-07-26 09:25 UTC, merged