Sidebar
LT-Students/DigitalOffice-frontend pull request #151
Opened 2021-07-23 16:04 UTC by Dimokku

1. Добавил sidebar, открытие по "бургеру" слева в шапке, закрытие по "Х" в самом sidebar. Линки пока как по макету

2021-07-24 12:36 UTC, NikGurev requested changes
Поправь это добавь пожалуйста несколько фич:

- Закрытие меню по нажатию вне компонента
- Закрытие меню по нажатию на вкладу
- сейчас при закрытии сайдбара кнопка меню остается активной, нужно посмотреть, как это исправить
- для каждой вкладки добавили иконку, подставь их тоже. Советую брать mat-icon, чтобы пока не зацикливаться на подстановку картинок

2021-07-24 12:36 UTC, NikGurev commented on src/app/shared/component/content-container/content-container.component.ts
> +	public navIsOpened: boolean = false;
- можно без Is

```suggestion
	public navOpened: boolean = false;
```
- присваивание значения делаем в конструкторе

2021-07-24 12:36 UTC, NikGurev commented on src/app/shared/component/header/header.component.ts
> +	@Output() public burgerClick = new EventEmitter();
- расположи Output после Input
- не очень нравится мне название, сразу кушать хочется. Давай лучше menuClick
- инициализация и присваивание значения также в конструкторе

2021-07-24 12:36 UTC, NikGurev commented on src/app/shared/component/content-container/content-container.component.scss
> +	}
не нравится мне абсолютное позиционирование. Никак нельзя с помощью флексов сделать?

2021-07-24 12:36 UTC, NikGurev commented on src/app/shared/component/content-container/content-container.component.ts
> +	}
- нет смысла передавать параметр, если он не используется. 
- если есть параметр, то нужно проставлять тип

2021-07-24 12:37 UTC, NikGurev requested changes

2021-07-24 12:37 UTC, NikGurev commented on src/app/shared/component/content-container/content-container.component.scss
> +		}
для компонента `mat-icon` необязательно подставлять курсор поинтер, они по дефолту такие

2021-07-24 14:48 UTC, Dimokku commented on src/app/shared/component/content-container/content-container.component.scss
> +		}
Странно, я сейчас проверил, у меня без курсор поинтера не меняется курсор, так и остается стрелочкой

2021-07-26 16:55 UTC, NikGurev requested changes

2021-07-26 16:55 UTC, NikGurev commented on src/app/shared/component/content-container/content-container.component.scss
> +		}
Почисти Кэш

2021-07-26 16:55 UTC, NikGurev commented on src/app/shared/component/content-container/content-container.component.ts
> +			this.closeNav()
- Лишняя проверка на **true** и на null
- Ругается на тип `PointerEvent` -  должен быть `MouseEvent`
- `;` после `this.closeNav()`
- Мне не очень нравится, что происходит проверка по селекторам - в Angular есть более удобные инструменты работы с DOM ([пример решения похожей задачи](https://stackoverflow.com/questions/51150422/how-to-detect-click-outside-of-an-element-in-angular)). Сделай шаблонную переменную на элемент сайдбара и с помощью нее делай проверку

2021-07-26 16:55 UTC, NikGurev commented on src/app/shared/component/content-container/content-container.component.html
> +		<span mat-flat-button doText color='gray1' class='sidenav__close-button' (click)="onCloseNavClick()">
Реализуй пожалуйста кнопку через `mat-icon-button`, а то мне не очень нравится, как тень отбрасывается

2021-07-29 08:02 UTC, NikGurev approved these changes

2021-07-29 08:03 UTC, merged