added second input for password on 2 and 3 pages in wizard.component.…
LT-Students/DigitalOffice-frontend pull request #168
Opened 2021-08-06 21:57 UTC by AnastassiaVarabei

…html

2021-08-10 11:24 UTC, tsinevik requested changes

2021-08-10 11:24 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +	hide = true;
Отсюда у тебя и баг, ты на всех инпутах обращаешься к этой переменной, чтобы переключать тип. Как только один глазик поменял значение, оно тут же у всех меняется. Надо подумать, как это иначе можно сделать. Есть вариант попробовать сделать свой инпут password, который как раз будет отслеживать это дело. Можно, конечно, пойти совсем по простому пути и сделать 4 переменные для каждого инпута, но это плохой вариант. Может быть, как-то через клик на глазик можно обратиться к инпуту и поменять у него тип. Но, скорее всего, первый вариант самый лучший - сделать отдельный инпут.

2021-08-10 17:31 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +import validate = WebAssembly.validate;
import { ErrorStateMatcher } from '@angular/material/core'; - в соответствии с документацией material input для динамического отражения сообщения об ошибках https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown

import validate = WebAssembly.validate; - удалила. Видно случайно внесла

2021-08-10 17:34 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +		let pass =  group.controls.password.value;
Пробел удалила

2021-08-10 18:01 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +			confirmPassword: ['']
Добавила confirmPassword: ['', Validators.required]

2021-08-10 18:05 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +		let confirmPass = group.controls.confirmPassword.value;
исправила: 
let pass = group.get('password').value;
let confirmPass = group.get('confirmPassword').value;

2021-08-10 18:07 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.html
> +                    <mat-label>Пароль</mat-label>
Внесла изменения в лейб

2021-08-11 11:40 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.html
>  					<input matInput formControlName="password" placeholder="Придумайте пароль" required />
Поставь на первые поля с паролем тип password по умолчанию

2021-08-12 18:35 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.html
>  					<input matInput formControlName="password" placeholder="Придумайте пароль" required />
поставила)

2021-08-12 18:36 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +	hide = true;
баг был в одинаковом свойстве для двух инпутов )

2021-08-12 18:37 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.html
>  					<input matInput formControlName="password" placeholder="Придумайте пароль" required />
поставила

2021-08-13 13:47 UTC, tsinevik requested changes

2021-08-13 13:47 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.html
> +                    <mat-icon matSuffix (click)="hidePassword = !hidePassword">{{hidePassword ? 'visibility_off' : 'visibility'}}</mat-icon>
У тебя всё ещё синхронизированы инпуты на разных страницах. Если нажать на глазик на второй странице, то на третьей он тоже переключится.
Можно, конечно, ещё две переменные добавить для этого, но я бы лучше всё же новый компонент для этого инпута написал. Ты мне ссылку скидывала на пример:
https://stackblitz.com/edit/angular-9ljkmd-vezw2d?file=app%2Fcustom-select%2Fcustom-select.component.ts

2021-08-13 13:47 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.html
> +                    <mat-icon matSuffix (click)="hidePassword = !hidePassword">{{hidePassword ? 'visibility_off' : 'visibility'}}</mat-icon>
В этом примере по сути компонент выступает просто обёрткой для mat-form-field и достаточно просто реализуются методы интерфейса ControlValueAccessor, который необходим для связывания кастомных полей формы с самой формой.

2021-08-13 13:47 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.html
> +                    <mat-icon matSuffix (click)="hidePassword = !hidePassword">{{hidePassword ? 'visibility_off' : 'visibility'}}</mat-icon>
Ну если совсем тяжко и непонятно, то ладно, пусть будут 4 переменные

2021-08-13 13:47 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.scss
>  	}
этот класс в принципе не нужен, можно удалить его

2021-08-13 13:47 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +	checkPasswords (group: FormGroup) {
пробельчик убрать и добавить возвращаемый тип

2021-08-22 15:52 UTC, tsinevik requested changes
см. личку в Slack

2021-08-22 15:52 UTC, tsinevik commented on src/app/shared/component/password/password.component.ts
> +  //constructor(public injector: Injector) { }
надо удалить

2021-08-22 15:52 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.ts
>  	submitForm() {
модификатор доступа и возвращаемый тип

2021-08-22 15:52 UTC, tsinevik commented on src/app/shared/component/password/password.component.scss
> +}
тут можно написать `width: inherit`. А в компоненте wizard, как и раньше ты делала, проставить на все поля классы или использовать грид

2021-09-06 20:07 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.scss
>  	}
удалила

2021-09-06 20:08 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +
удалила

2021-09-06 20:08 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +	public myForm: null;
удалила

2021-09-06 20:10 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.ts
>  	smtpForm: FormGroup;
поставила public

2021-09-06 20:15 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +						enableSsl: this.smtpForm?.get('enableSsl')?.value,
убрала

2021-09-06 20:15 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.html
> +    </label>
убрала

2021-09-06 20:15 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.ts
> +  //constructor(public injector: Injector) { }
удалила

2021-09-06 20:22 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.scss
> +}
внесла корректировки

2021-09-07 16:31 UTC, tsinevik requested changes

2021-09-07 16:31 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +	matchControls(field1: string | (string | number)[], field2: string | (string | number)[]) {
Первый комментарий всё ещё актуален

2021-09-07 16:31 UTC, tsinevik commented on src/app/shared/component/password/password.component.ts
> +	isErrorState(control: FormControl | null, form: FormGroupDirective | NgForm | null): boolean {
Добавить модификатор доступа

2021-09-07 16:31 UTC, tsinevik commented on src/app/shared/component/password/password.component.ts
> +	public value: any;
удалить переменную, она нигде не используется

2021-09-07 16:31 UTC, tsinevik commented on src/app/shared/component/password/password.component.ts
> +	hide = true;
перенести инициализацию в конструктор, добавить модификаторы доступа и типы данных

2021-09-07 16:31 UTC, tsinevik commented on src/app/shared/component/password/password.component.ts
> +	};
перенести инициализацию в конструктор, добавить модификаторы доступа и типы данных

2021-09-07 16:31 UTC, tsinevik commented on src/app/shared/component/password/password.component.ts
> +	setValue(value: string) {
Добавить модификаторы доступа

2021-09-07 16:43 UTC, tsinevik requested changes

2021-09-07 16:43 UTC, tsinevik commented on src/app/shared/component/password/password.component.html
> +        {{ placeholder }}
Поставить понятную ошибку, что поле обязательное

2021-09-07 16:51 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +				? { errorMatch: 'Пароль не совпадает' }
непонятное название свойства ошибки errorMatch - оно говорит лишь о том, что ошибка подтверждена, а какая ошибка?

2021-09-08 17:17 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.ts
> +	isErrorState(control: FormControl | null, form: FormGroupDirective | NgForm | null): boolean {
добавила

2021-09-08 17:18 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.ts
> +	public value: any;
удалила

2021-09-08 17:26 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.ts
> +	setValue(value: string) {
добавила public

2021-09-09 16:47 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.ts
>  	submitForm() {
добавила

2021-09-09 19:40 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.ts
> +	hide = true;
инициализировала и добавила модификаторы доступа и типы данных

2021-09-09 21:17 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.ts
> +	matchControls(field1: string | (string | number)[], field2: string | (string | number)[]) {
добавила

2021-09-19 10:26 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.ts
> +	};
перенесла и добавила

2021-09-19 11:05 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.html
> +        {{ placeholder }}
Написала "Поле обязательное"

2021-09-21 18:25 UTC, tsinevik requested changes

2021-09-21 18:25 UTC, tsinevik commented on src/app/shared/component/password/password.component.ts
> +} from '@angular/forms';
Много неиспользуемых импортов

2021-09-21 18:25 UTC, tsinevik commented on src/app/shared/component/password/password.component.ts
> +}
Если при совпадающих паролях хотя бы одно другое поле имеет ошибку, пароли всё равно красным подсвечиваются, будто в них ошибка есть. Это правится в этом месте

2021-09-21 18:25 UTC, tsinevik commented on src/app/shared/component/password/password.component.ts
> +	control = new FormControl(null, [ Validators.required ]);
Мы инициализируем переменные в конструкторе. И у контрила не хватает модификатора доступа

2021-09-21 18:25 UTC, tsinevik commented on src/app/shared/component/password/password.component.html
> +        {{ 'Поле обязательное' }}
Скобки и кавычки не нужны

2021-09-21 18:25 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.scss
> +		}
По БЭМу у элемента не может быть ещё одного элемента, только у блока может быть несколько элементов.
И width в принципе не может быть названием элемента, это скорее название модификатора, у тебя этот класс относится к полям формы, поэтому ему надо дать соответствующее название.

2021-09-21 18:25 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.html
> +                    </do-password>
Непонятно, почему ты этот класс только этим двум полям дала, а не всем. Они у тебя сейчас разных длин

2021-09-21 18:25 UTC, tsinevik commented on src/app/app.module.ts
> +	imports: [ AppRoutingModule, CoreModule, AuthModule, UserModule, AdminModule, EmployeeModule, NgbModule, MaterialModule, InstallerModule, FormsModule ],
Непонятно откуда отступы взялись, у нас файлы должны форматироваться и приводиться к общему виду при коммите

2021-09-21 18:25 UTC, tsinevik commented on src/app/app.module.ts
> +	schemas: [ CUSTOM_ELEMENTS_SCHEMA ],
здесь то же самое

2021-09-21 18:25 UTC, tsinevik commented on yarn.lock
>  "@angular-eslint/eslint-plugin@0.6.0-beta.0":
Во всём этом файле не должно быть изменений, он должен выглядеть как в девелопе

2021-09-23 17:19 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.html
> +<mat-form-field class='password' appearance='fill' FormGroupDirective>
удалила

2021-09-23 17:20 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.ts
> +	public setValue(value: string) {
добавила void

2021-09-23 17:21 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.ts
> +	public writeValue(value: any): void {
изменила any на string

2021-09-23 17:22 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.ts
> +} from '@angular/forms';
удалили неиспользуемые

2021-09-23 17:52 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.ts
> +}
исправила

2021-09-23 19:23 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.html
> +                    </do-password>
прописала для всех input

2021-09-23 19:24 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.scss
> +		}
переименовала

2021-09-23 19:25 UTC, AnastassiaVarabei commented on src/app/app.module.ts
> +	imports: [ AppRoutingModule, CoreModule, AuthModule, UserModule, AdminModule, EmployeeModule, NgbModule, MaterialModule, InstallerModule, FormsModule ],
отступы удалила

2021-09-23 19:26 UTC, AnastassiaVarabei commented on src/app/app.module.ts
> +	schemas: [ CUSTOM_ELEMENTS_SCHEMA ],
удалила отступы

2021-09-23 19:26 UTC, AnastassiaVarabei commented on yarn.lock
>  "@angular-eslint/eslint-plugin@0.6.0-beta.0":
сегодня подтянула develop

2021-09-23 20:26 UTC, tsinevik requested changes

2021-09-23 20:26 UTC, tsinevik commented on src/app/modules/installer/components/wizard/wizard.component.html
> +                    </do-password>
Инпуты паролей всё ещё длиннее на 1 пиксель остальных полей. Также если добавить какому-то полю matSuffix или matPrefix, то это поле станет шире остальных.

2021-09-23 20:26 UTC, tsinevik commented on src/app/shared/component/password/password.component.html
> +        {{ 'Поле обязательное' }}
Это всё ещё актуально

2021-09-23 20:26 UTC, tsinevik commented on src/app/shared/component/password/password.component.ts
> +	control = new FormControl(null, [ Validators.required ]);
Это тоже всё ещё актуально

2021-09-23 20:26 UTC, tsinevik commented on yarn.lock
>  "@angular-eslint/eslint-plugin@0.6.0-beta.0":
Этот файл всё ещё отличается от того, что в девелопе лежит

2021-09-24 15:09 UTC, AnastassiaVarabei commented on src/app/modules/installer/components/wizard/wizard.component.html
> +                    </do-password>
перенесла класс на mat-form-field

2021-09-24 15:13 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.html
> +        {{ 'Поле обязательное' }}
Скобки и кавычки удалила

2021-09-24 15:28 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.ts
> +	control = new FormControl(null, [ Validators.required ]);
исправила

2021-09-24 16:12 UTC, tsinevik requested changes

2021-09-24 16:12 UTC, tsinevik commented on src/app/shared/component/password/password.component.scss
> +	width: 205px;
ну тут же всё правильно было, тебе нужно наследовать ширину от родителя, а не ту ставить фиксированную. Если мы в другом месте захотим использовать эту компоненту, но с другой шириной, то как мы переопределять её будем?

2021-09-24 16:37 UTC, AnastassiaVarabei commented on src/app/shared/component/password/password.component.scss
> +	width: 205px;
вернула inherit

2021-09-24 16:38 UTC, tsinevik approved these changes

2021-09-24 16:44 UTC, merged