Improvement/datapicker
LT-Students/DigitalOffice-frontend pull request #169
Opened 2021-08-07 10:48 UTC by Evgenia1394

changed function for datapicker

2021-08-07 11:35 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.html
> +                           {{ startDate | date: 'LLLL YYYY' | titlecase }}
startDate.value должно быть

2021-08-07 11:35 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.html
> +                               (monthSelected)="chosenMonthHandler($event, picker)"
(monthSelected)="picker.close()"

2021-08-07 11:35 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.ts
> +	public startDate: Date = new FormControl(new Date()).value;
у тебя эта переменная не дата, а форм контрол, который хранит дату. Поэтому надо убрать value

2021-08-07 11:35 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.ts
> +	}
удалить метод

2021-08-09 12:43 UTC, tsinevik requested changes

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.scss
> +		}
Лишний класс

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.scss
>  		align-items: center;
Не нравится мне абсолютное позиционирование, по крайней мере как оно у тебя тут устроено. Оно у тебя не по центру всё равно сейчас, если будешь изменять размеры окна, то заметишь. Погугли, как по центру позиционировать и график, и текст внутри.
И нижняя часть стилей тебе не нужная, у тебя время должно быть в одном-двух инлайн элементах

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.scss
>  		}
Не надо настраивать шрифты в этих стилях без острой необходимости.

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.scss
> +	}
Удалил класс, визуально ничего не изменилось, думаю, он не нужен

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.scss
> +	}
Убрал все стили, ничего не изменилось

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.scss
> +	}
Тебе в классах стрелочек нужен только бэкграунд колор, а для него у нас есть отдельные классы. Т.е. тебе специальный класс для этих кнопок в принципе не нужен

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.scss
> +	}
этот класс не нужен

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.scss
> +	&__hiding {
глаголы в названии не используем

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.scss
> +			color: #ff8a65;
Убрать. Ты на элементе используешь директиву doText, у которой есть свойство color, используй его

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.ts
> +	@ViewChild('canvas', { static: true }) canvas: ElementRef<HTMLCanvasElement>; //получили канву
такие комментарии лучше не оставлять. Тут и по контексту видно, что мы получаем канвас.

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.ts
> +	}
Не хватает модификатора доступа (public, private, protected) и возвращаемого типа

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.ts
> +	}
Не нравится мне такой нейминг, мб лучше что-то вроде onNextMonthClicked.
Какое и зачем значение возвращают эти функции?

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.ts
> +	}
Везде нужно добавить возвращаемый тип

2021-08-09 12:43 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.ts
> +	}
И я бы подумал, как изменить функции changeMonth, чтобы её ещё и здесь можно было использовать, чтобы не дублировать код.

2021-08-09 12:48 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.html
> +		</div>
и всё же бы я подумал, как эту часть реализовать через API диаграммы, которая позволяет отображать так тэги

2021-08-09 18:37 UTC, Evgenia1394 commented on src/index.html
> +  <body class="mat-typography">
нет

2021-08-09 18:54 UTC, Evgenia1394 commented on package.json
> +    "chart.js": "^2.9.4",
не помню, не трогала вроде в этом файле chart. Единственное делала команду npm install chart.js, думала что мне его нужно установить в проект, может тогда и обновилось. Обратно вернуть?

2021-08-10 19:27 UTC, Evgenia1394 commented on src/app/modules/user/components/chart/doughnut-chart.component.scss
> +	}
из doughnut убрала, если из diagram-wrapper - всё едет

2021-08-11 13:56 UTC, Evgenia1394 commented on src/styles.scss
> +body { margin: 0; font-family: Roboto, "Helvetica Neue", sans-serif; }
удалила этот импорт

2021-08-11 13:56 UTC, Evgenia1394 commented on src/stylesheets/base/_variables.scss
> +$dark_5: #424242;
это я

2021-08-13 16:04 UTC, Evgenia1394 commented on src/app/modules/user/components/chart/doughnut-chart.component.scss
> +			color: #ff8a65;
тут если пользоваться директивой цветом вся надпись оранжевой будет <h2 doText color="accent_color_bright" underlined underlinedSize="sm" class="chart__title">

2021-08-13 17:19 UTC, Evgenia1394 commented on src/app/modules/user/components/chart/doughnut-chart.component.ts
> +	}
а изначально же была одна функция вместо этих трех, сейчас обратно вернуть?

2021-08-15 16:14 UTC, tsinevik requested changes

2021-08-15 16:14 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.ts
> +		this.ctx = this.canvas.nativeElement.getContext('2d'); //приводит к созданию объекта
я просил убирать эти комментарии

2021-08-15 16:14 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.ts
> +		this.projectsLabels = this.projects.map(({ name }) => name);
projectsLabels можно спокойно сделать локальной переменной в этой функции, а не выносить в отдельное свойство этого класса

2021-08-15 16:14 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.ts
> +				},
По нажатию на элементы легенды у тебя из графика скрываются данные за какой-либо проект, нужно убрать эту возможность. Для этого надо переопределить в этом объекте свойство onClick

2021-08-15 16:14 UTC, tsinevik commented on src/app/modules/user/components/chart/doughnut-chart.component.html
> +	<div class="chart">
Раз у нас легенда через диаграмму отображается, то эта обёртка больше не нужна, а класс Chart можно перенести в mat-card

2021-08-30 13:34 UTC, Dimokku approved these changes

2021-08-30 13:39 UTC, tsinevik approved these changes

2021-08-30 13:39 UTC, merged