Improvement/team statistics
LT-Students/DigitalOffice-frontend pull request #202
Opened 2021-09-06 17:43 UTC by Evgenia1394

added team-statistics

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/admin/components/team-statistics/team-statistics.component.scss
> +		color: $gray1;
Дабы оградить тебя от лукавого, лучше на нужные спаны используй директиву doText совместно с атрибутом color='gray1'. В целом эта директива используется для стилизации текста. Можно ещё с помощью класса text_color_gray1. Вообще посмотри файлы _fonts.scss и _variables.scss в stylesheets

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/admin/components/team-statistics/team-statistics.component.html
> +                        <img src='assets/images/Vector.png'><img>
У нас в assets есть svg-шки, там есть значок edit, используй его

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	hoursProject?: number;
projectHours, с английской точки зрения, будет правильнее, т.к. часы проекта, а не проект часов

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	numberProjects?: string;
Та же история, projectsNumber, либо numberOfProjects)

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/admin/components/team-statistics/team-statistics.component.scss
> +}
Вообще мы пишем по БЭМ методологии, которой тут явно нет. Надо почитать и переделать в соответствие с БЭМом, и эти изменения также касаются html (но это само собой вытекающее)

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	public startDate = new Date();
Атата, инициализируем в конструкторе, и не забудь тип переменной указать

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	dataSource = this.DATA;
Не знаю, что из этого останется точно, но как свяжешь с бэком, надо будет все объявляемые переменные инициализировать в конструкторе, либо добавлять возможный тип undefined, тогда необходимость инициализировать отпадёт, но это лайфхак, без надобности не используй

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	public chosenMonthHandler(chosenDate: Date) {
Удобно, когда указываешь возвращаемый тип данных, так что лучше указать

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	public changeMonth(changeDate: number) {
Тоже укажи возвращаемый тип данных

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/user/components/project-page/project-page.component.html
> -<div class="card card_standard">
Не уд0ляй, подумай

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/user/components/project-page/project-page.component.scss
>  			background-color: #f5f5f5;
Как и с text_color_{colorName} можно использовать класс для цветов бэкграунда bg-{colorName}

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/user/components/project-page/project-page.component.scss
> +		background-color: $light_1;
bg-{colorName}

2021-09-07 12:34 UTC, Dimokku commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	ngOnInit(): void {
Не используется, лучше удалить

2021-09-07 14:49 UTC, tsinevik requested changes

2021-09-07 14:49 UTC, tsinevik commented on src/app/core/services/modal.service.ts
> +	TEAM_STATISTICS,
Ты это нигде не используешь

2021-09-07 14:49 UTC, tsinevik commented on src/app/data/api/project-service/models/project-info.ts
> +  createdAtUtc?: any;
Так, никогда ни в коем случае просто так не меняй ничего в директории api, по-моему, я уже об этом говорил. У нас тут файлы сами генерируются, то, что ты здесь написала может исчезнуть при следующем обновлении сервиса. Тебе просто надо было подтянуть девелоп, т.к. в нём уже всё как надо

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.ts
> +import { NewEmployeeComponent } from '../../modals/new-employee/new-employee.component';
Тут, конечно, ничего критичного, но почему вдруг эта строка вниз ушла?

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	@ViewChild(MatSort) sort: MatSort | undefined;
MatSort у тебя не используется

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	public startDate = new Date();
и я бы назвал переменную selectedDate, потому что при смене месяца в дейтпикере у нас эта переменная содержит уже не начальную дату

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	dataSource = this.DATA;
1. dataSource не используется
2. у displayedColumns не хватает модификатора доступа и типа, хотя в принципе не совсем понятно, почему хэдэр таблицы ты решила именно через массив сгенерировать

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	constructor(private _userService: UserService, private cdr: ChangeDetectorRef) {
cdr не используется и приватные переменные мы начинаем с нижнего подчеркивания, то есть _cdr

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	public changeMonth(changeDate: number) {
Этот метод у тебя вообще не используется

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.scss
> +}
По БЭМу мы не обращаемся напрямую к тэгам, более того ты используешь в html глобальные классы table, а в локальном файле зачем-то переопределяешь их

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.html
> +                    <ng-template #defis>
надо давать более понятные названия переменным, defis лишь говорит о том, что внутри, вероятно, хранится дефис, но не для чего он нужен

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	numberProjects?: string;
или projectsCount

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/user/components/project-page/project-page.component.ts
> +	};
инициализируем в конструкторе

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/user/components/project-page/project-page.component.ts
> +	public svgActiveTabColorP: string;
эти переменные не нужны

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/user/components/project-page/project-page.component.ts
> +		}
Это можно реализовать в темплейте с помощью свойства isActive у таба, хотя надо подумать, как правильнее это реализовать, чтобы не заводить на каждый таб по переменной

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/user/components/project-page/project-page.component.scss
> +	fill: $gray1;
Марджины абсолютно никакого отношения не имеют к цвету, а у тебя классы именно цвет означают. И эти классы, скорее всего, не нужны, вместо них можно попробовать использовать глобальные классы цвета.

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/user/components/project-page/project-page.component.html
> +                    <ng-template  mat-tab-label class='white'>
класса white не существует

2021-09-07 14:49 UTC, tsinevik commented on src/app/modules/user/components/project-page/project-page.component.html
> +                            </svg>
иконки я бы вынес в отдельный файл свг и их надо обернуть в mat-icon

2021-09-07 17:48 UTC, Evgenia1394 commented on src/app/modules/admin/admin.module.ts
> +	exports: [DndDirective, TeamStatisticsComponent],
она создана в admin, но доступ к ней должен быть из модуля user (src/app/modules/user/components/project-page/project-page.component.html) поэтому скорее всего и экспорт нужен.

2021-09-07 19:31 UTC, Evgenia1394 commented on src/app/modules/admin/components/team-statistics/team-statistics.component.scss
> +		color: $gray1;
очень своевременный комментарий, я как раз не умела doText директивой пользоваться) Просто копировала оттуда, где найду что-то похожее)) Оказывается в файле text.directives они все есть)

2021-09-07 21:26 UTC, Dimokku commented on src/app/modules/admin/admin.module.ts
> +	exports: [DndDirective, TeamStatisticsComponent],
В таком случае да

2021-09-08 16:59 UTC, Evgenia1394 commented on src/app/modules/admin/components/department-card/department-card.component.ts
> +import { NewEmployeeComponent } from '../../modals/new-employee/new-employee.component';
выходило сообщение о том, что какой-то из сервисов, должен быть импортирован раньше чем NewEmployeeComponent.

2021-09-13 10:52 UTC, tsinevik requested changes

2021-09-13 10:52 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.html
> +                    <ng-template #defis>
Это всё ещё актуально

2021-09-13 10:52 UTC, tsinevik commented on src/app/modules/user/components/project-page/project-page.component.html
> +<div class='table__header-wrapper bg-light_1'>
Здесь надо было mat-card оставить. И классы те же, вроде бы, оставить.
А класс "table__header-wrapper" тут вообще ни к месту, блок table вообще никак не относится к этому элементу

2021-09-13 10:52 UTC, tsinevik commented on package-lock.json
> +  "version": "0.3.0",
Ты, видимо, как-то не совсем правильно решила конфликт, потому как у тебя должна быть версия 0.3.1 здесь

2021-09-13 10:52 UTC, tsinevik commented on package-lock.json
> +    },
И вот это непонятно откуда взялось, т.к. в девелопе такого нет, а у самого Chart.js версия 3.5.1. Надо как-то повторно смержить девелоп

2021-09-13 21:42 UTC, tsinevik approved these changes

2021-09-13 21:42 UTC, merged