Feature/team statistic
LT-Students/DigitalOffice-frontend pull request #206
Opened 2021-09-15 20:28 UTC by Dimokku

2021-09-16 11:42 UTC, tsinevik requested changes

2021-09-16 11:42 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.html
> +                            <img class="avatar__photo" src='assets/images/smallPhoto/Ellipse91.png'>
используй компонент profile-image в shared

2021-09-16 11:42 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.html
> +                        <td [ngClass]="{'cell': true, 'cell__leaves': employee.leaves?.length! > 1}">
если cell всегда активен, то и в ngClass его нет смысла добавлять, используй его в class

2021-09-16 11:42 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +		this.employees$ = new Observable();
ты можешь прямо здесь присвоить getEmployees

2021-09-16 11:42 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +				this._cdr.markForCheck();
Чисто ради интереса, а без markForCheck не работает?

2021-09-16 11:42 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	managerHours?: number | null;
А для чего тут null?

2021-09-16 11:42 UTC, tsinevik commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +export interface EmployeeInformation {
Мб правильнее назвать EmployeeStats или EmployeeStatistics, информация - понятие расстяжимое, больше под персональную информацию подходит

2021-09-16 15:45 UTC, Dimokku commented on src/app/modules/admin/components/team-statistics/team-statistics.component.ts
> +	managerHours?: number | null;
null у неймов убрал, а у часов он необходим, т.к. на бэке у них тоже возможны такие значения

2021-09-17 10:33 UTC, tsinevik submitted a review, later dismissed

2021-09-17 10:38 UTC, tsinevik approved these changes

2021-09-17 10:38 UTC, merged