Improvement/edit departament
LT-Students/DigitalOffice-frontend pull request #212
Opened 2021-09-25 15:38 UTC by Evgenia1394

2021-09-27 10:56 UTC, tsinevik requested changes
При успешном редактировании департамента данные на странице департамента остаются старыми, нужно поправить

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.scss
> +			margin-top: 52px;
тут марджин не нужен

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.scss
> +			margin-top: 52px;
Также класс title выше тоже можно удалить и убрать его из теплейте

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.html
> +        <div class='department__info__header'>
название класса не по БЭМу

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.html
>  <h1 class="title">{{ departmentInfo?.name }}</h1>
класс title не нужен

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.scss
>  		border-bottom: 1px solid #fafafa;
эту полоску можно на mat-divider заменить

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.html
> +                </div>
1. директивы doText у нас больше нет, поэтому не используем её больше
2. непонятно зачем тут div, картинку и текст можно спокойно в внутри кнопки оставить
3. непонятно почему ты клик назначаешь на див, а не на саму кнопку
4. тебе не надо передавать в в onEditDepartment ничего, у тебя эта переменная и так хранится в компоненте
5. alt не должен быть пустым
6. у тебя иконка и лейбл не по центру находятся

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.html
> +    <h3>{{!isEdit ? "Создание департамента" : "Редактирование департамента"}}</h3>
куда mat-dialog-title ушёл?

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.ts
> +		};
1. не let, а const
2. зачем ты создаешь экземпляр конфига? Тебе нужно просто создать объект с нужными тебе полями. Свойство data тоже не нужно

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.ts
> +		};
И ты передаешь не конфиг, а данные, название переменной тоже надо поправить

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.ts
> +}
интерфейс используется один раз и вообще некорректно. Ты передаешь в модалку объект MatDialogConfig, но при этом говоришь, что это на самом деле EditModalContentConfig, хотя у тебя они по структуре различаются

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.ts
> +	onEditDepartamentClick(departmentInfo: DepartmentInfo | undefined): void {
модификатор доступа поставь

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.scss
> +	}
класс нигде не используется

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +	private dataToEdit: any;
у private переменных и функций мы перед названием ставим нижнее подчёркивание, т.е. `_dataToEdit`

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +	private dataToEdit: any;
тип не any

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +		@Inject(MAT_DIALOG_DATA) data: MatDialogConfig
вот здесь ты как раз могла бы использовать EditModalContentConfig, а не MatDialogConfig

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +		private dialogRef: MatDialogRef<NewDepartmentComponent>,
нижнее подчёркивание

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +	public departmentInfo: DepartmentInfo | undefined;
это поле нигде не используется

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +	public chooseModal() {
ты здесь выбираешь какое действие сделать или, если общими словами, сабмитишь форму, а не выбираешь модалку, модалка у тебя одна и она уже открыта

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +	private dataToEdit: any;
Плохое название переменной, у тебя тут хранится информация о департаменте, да и в принципе конкретно эта переменная не участвует в редактировании

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +		}
у тебя всегда сначала создается форм группа для нового департамента, а потом по условию уже создается форма для редактирования. Она должна создаваться один раз

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +			const editBody = Object.keys(this.departmentForm.controls).reduce((acc: any, key) => {
тип не any

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +			const editBody = Object.keys(this.departmentForm.controls).reduce((acc: any, key) => {
и вообще здесь можно тип опустить

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +					const objToSend = {
непонятное название, объект для отправки, какой объект, куда отправить? Непонятно

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +				return acc
точка с запятой

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +			.subscribe((result: any) => {
не any

2021-09-27 10:56 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.html
> +            <button mat-flat-button color="primary" type="submit" [disabled]="departmentForm.pristine">Сохранить</button>
кнопка будет активна, если изменить значение и вернуть его к изначальному

2021-09-29 17:51 UTC, Evgenia1394 commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +	public departmentInfo: DepartmentInfo | undefined;
ты про все три переменные?

2021-10-03 14:34 UTC, tsinevik requested changes

2021-10-03 14:34 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.html
> +                        class='bg-light_2 employee-info__input'
эти классы нужно убрать

2021-10-03 14:34 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.html
> +                        matInput type="text"
type у textarea, по-моему, всегда текст

2021-10-03 14:34 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.ts
> +export interface EditModalContentConfig {
Это не config, можно убрать это слово

2021-10-03 14:34 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +	private readonly departamentInfo: EditModalContentConfig;
private переменные должны начинаться с нижнего подчёркивания

2021-10-03 14:34 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +		}
Так, ты тут мало того, что через чур переусложнила код, так и не поняла суть замечания. Ты всё ещё дважды создаёшь форму в случае, если мы редактируем департамент. Самый простой, наверно, - это для каждого поля в начальном значении указывать с помощью тернарного оператора (или упрощенного оператора ??) соответствующее свойство departmentInfo.

2021-10-03 14:34 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +		}
Внутри `if (this.departmentInfo)` происходит что-то очень странное и непонятно, зачем столько проверок вообще?

2021-10-03 14:34 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +		// .pipe(map((response) => response.body));
Этот код не используется

2021-10-03 14:34 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +			}
тут, в принципе, тебе должен сам вебшторм предложить, как это место можно упростить, но вообще тут можно флагу isFormChanged присвоить логическое выражение из if

2021-10-05 14:48 UTC, tsinevik requested changes

2021-10-05 14:48 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.ts
> +	directorid?:  string,
1. непонятно откуда у name взялся ValidationErrors и null, у нема не может быть таких значений
2. в дескрипшн у тебя по факту дважды указан тип undefined, вопрос у свойства означает, что он опциональный и по умолчанию undefined

Ты должна была посмотреть, какие значения может принимать департамент в DepartmentInfo и на этой основе расставить типы в этом интерфейсе

2021-10-05 14:48 UTC, tsinevik commented on src/app/modules/admin/components/department-card/department-card.component.ts
> +			directorid: this.departmentInfo?.director?.id ? this.departmentInfo?.director?.id : '',
1. в нейме ты приводишь значение к строке, хотя оно может быть undefined, почему не сделала, как с двумя свойствами ниже?
2. дескрипшн и директор айди ты всегда присваиваешь строку, но при этом в интерфейсе указала и какие-то другие возможные значения

2021-10-05 14:48 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +	public _isEdit: boolean | undefined;
не понял, почему свойству паблике ты нижнее подчёркивание решила добавить

2021-10-05 14:48 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +			directorid: this._departamentInfo ? this._departamentInfo.directorid : [ '' ],
надо только значение менять, а не весь массив
`name: [ this._departamentInfo ? this._departamentInfo.name : '', Validators.required ],`

2021-10-05 14:48 UTC, tsinevik commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> +		this._isEdit = true}
а в противном случае isEdit = undefined, что не есть хорошо. Нужно привести departmentInfo к булеву значение и присвоить это значение переменной isEdit

2021-10-06 09:46 UTC, merged