Лента новостей
LT-Students/DigitalOffice-frontend pull request #215
Opened 2021-10-02 18:37 UTC by Dimokku

1. Свёрстано (почти)
2. Связано с бэком
3. Добавлена библиотека ngx-infinite-scroll

2021-10-03 22:42 UTC, tsinevik requested changes

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/news-feed/news-feed.component.html
> +            <img src="../../../../../assets/svg/Plus Add.svg" alt="plus">&nbsp;
пробелы в названиях файлов лучше не использовать

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/news-feed/news-feed.component.html
> +            <img src="../../../../../assets/svg/Plus Add.svg" alt="plus">&nbsp;
вообще не очень понял, зачем ты тут картинку используешь, у материала есть же иконка add
и в mat-icon надо оборачивать иконки

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/news-feed/news-feed.component.html
> +            <span>Добавить новость</span>
а почему ты в span решил обернуть текст?

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/news-feed/news-feed.component.html
> +        <div class="feed" *ngIf="articlePreviews.length > 0">
а если длина массива равна нулю, то цикл же просто ничего не выведет, зачем тут это проверка?

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/news-feed/news-feed.component.html
> +                        <img src="../../../../../assets/svg/more-gray.svg" alt="more">
надо оборачивать в mat-icon и у материала есть иконка more_horiz

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/news-feed/news-feed.component.scss
> +}
feed - это грид в гриде, но непонятно зачем

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/news-feed/news-feed.component.scss
> +}
я так предполагаю, что мб из-за этого или из-за max-content при сжатии окна вёрстка не адаптируется

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/news-feed/news-feed.component.ts
> +	}
переменной `fixedTags` можно присвоить значение логического выражения из if'а,  это будут эквивалентные записи

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/news-feed/news-feed.component.ts
> +	public onMenuOpen(event: any): void {
у ивентов есть вполне свой тип данных

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/post/post.component.html
> +        <img src="../../../../../assets/svg/close-icon.svg" alt="close">
обернуть в mat-icon, а материала есть иконка close

2021-10-03 22:42 UTC, tsinevik commented on src/app/core/models/news.model.ts
> +	content: any;
тут явно не any должен быть тип

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/news-feed/news-feed.component.ts
> +		let params: IFindNewsRequest = {
ты не переприсваиваешь значение этой переменной, поэтому тут нужно использовать const

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/post/post.component.ts
> +		this.article$ = new Observable(undefined);
непонятно зачем здесь undefined

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/post/post.component.ts
> +					let notHiddenBlocks = blocks.filter((block: any) => (block?.tunes && block.tunes?.previewTune) ? !block.tunes.previewTune.hidden : true);
не let, а const

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/components/post/post.component.ts
> +					let notHiddenBlocks = blocks.filter((block: any) => (block?.tunes && block.tunes?.previewTune) ? !block.tunes.previewTune.hidden : true);
block у тебя не any

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/parser.ts
> +							let contentClasses: string[] = ["ce-block__content"];
не let, а const

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/parser.ts
> +							let src = `data:image/${image.body?.extension?.slice(1)};base64,${image.body?.content}`
не let, а const

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/parser.ts
> +								if (block.data.withBackground)
почему у тебя тут два одинаковых ифа?

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/parser.ts
> +				if (block.data.aligment) style = `text-align: ${block.data.aligment}`
фигурные скобки

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/parser.ts
> +					});
фигурные скобки
не let, а const

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/parser.ts
> +		)
фигурные скобки

2021-10-03 22:42 UTC, tsinevik commented on src/app/modules/news/parser.ts
> +		)
или через тернарные оператор написать

2021-10-03 22:42 UTC, tsinevik commented on src/app/shared/component/header/header.component.scss
> +	height: var(--header-height);
напомни, почему ты здесь просто не мог завести sass-переменную?

2021-10-03 23:06 UTC, Dimokku commented on src/app/core/services/news/news.service.ts
> +		return this._newsService.editNews({ newsId, body })
Нейн, скорее всего я был пьян и обдолбан, т.к. знаю, что ты любишь точки с запятыми)

2021-10-04 11:53 UTC, Dimokku commented on src/app/modules/news/components/news-feed/news-feed.component.html
> +            <span>Добавить новость</span>
Чтобы иконка и текст были центрированы, без этого стиль .header__button text-align: center не работает на "Добавить новость"

2021-10-04 13:04 UTC, Dimokku commented on src/app/shared/component/header/header.component.scss
> +	height: var(--header-height);
Немного порылся по теме импорта переменных в компоненту (не в scss, а в ts), но особо ничего не нашёл по именно sass-переменным, простейший способ это через рут и css переменную

2021-10-04 13:32 UTC, tsinevik approved these changes

2021-10-04 13:33 UTC, merged