Feature/title datepicker
LT-Students/DigitalOffice-frontend pull request #218
Opened 2021-10-04 22:12 UTC by Randattt

Таймлист не запускался, так что ориентировался на 2 компонента в разделе "Учет времени".
Там теперь используется созданный  компонент вместо прежнего html кода.

2021-10-05 11:18 UTC, tsinevik requested changes
В компонентах timelist и team-statistics тоже надо заменить заголовки на компонент. Понимаю, что таймлист временно не работает и на него не попасть, но заменить внутри компонента его можно.

2021-10-05 11:18 UTC, tsinevik commented on src/app/shared/component/title-datepicker/title-datepicker.component.ts
> +	}
так, вот этот сервис имеет очень специфичное предназначение - он используется только на странице учёта времени для синхронизации нескольких компонентов. Соотвественно, если мы будем использовать компонент на других страницах, то он не должен зависеть от этого сервиса. Компонент должен принимать через @Input какое-то значение и при изменении эмиттить событие с помощью @Output, которое будет обрабатываться уже в родительских компонентах.

2021-10-05 11:18 UTC, tsinevik commented on src/app/shared/component/title-datepicker/title-datepicker.component.ts
> +	}
Эти функции, видимо, случайно сюда попали из блока с диаграммой? Эти функции не используются

2021-10-05 11:18 UTC, tsinevik commented on src/app/shared/component/title-datepicker/title-datepicker.component.html
> +    {{text}} &nbsp;
тут два пробела получается, это так и задумано?

2021-10-05 11:22 UTC, Randattt commented on src/app/shared/component/title-datepicker/title-datepicker.component.scss
> +.hidden-form {
Согласен, я заменю на hidden-field, так понятнее суть будет

2021-10-05 11:23 UTC, Randattt commented on src/app/shared/component/title-datepicker/title-datepicker.component.ts
> +	}
+, уже ехал домой с мыслью, что их надо убрать)

2021-10-05 11:24 UTC, Randattt commented on src/app/shared/component/title-datepicker/title-datepicker.component.html
> +    {{text}} &nbsp;
нет, это я не доглядел

2021-10-06 09:44 UTC, tsinevik requested changes
На странице учёта времени у нас все три блока связаны общей датой, если меняешь дату в одном месте, то она должна поменяться и в другом. У тебя же если сейчас поменять дату в одном блоке, то в других останется старая. Для этого нужно добавить возможность получать начальное значение дейтпикера извне. Тут понадобится ещё одна инпут-переменная.

2021-10-06 09:44 UTC, tsinevik commented on src/app/shared/component/title-datepicker/title-datepicker.component.ts
> +	public selectDate: Date = new Date()
Мы инициализируем переменные внутри конструктора, это у нас стиль написания кода такой

2021-10-06 19:42 UTC, tsinevik approved these changes

2021-10-06 19:42 UTC, merged