Modal for adding stuff to department
LT-Students/DigitalOffice-frontend pull request #231
Opened 2021-10-07 14:35 UTC by Randattt

2021-10-07 18:45 UTC, tsinevik requested changes

2021-10-07 18:45 UTC, tsinevik commented on src/app/shared/modals/add-employee/add-employee.component.html
> +        </button>
эту часть нужно заменить на `<mat-icon matPrefix>search</mat-icon>` внутри mat-form-field инпута. Почитай про mat-form-field и mat-icon
https://material.angular.io/components/form-field/overview#prefix--suffix

2021-10-07 18:45 UTC, tsinevik commented on src/app/shared/modals/add-employee/add-employee.component.html
> +            <input matInput placeholder="Романов Владислав" value="">
добавь тип search

2021-10-07 18:45 UTC, tsinevik commented on src/app/shared/modals/add-employee/add-employee.component.html
> +            <input matInput placeholder="Романов Владислав" value="">
value не нужен

2021-10-07 18:45 UTC, tsinevik commented on src/app/shared/modals/add-employee/add-employee.component.html
> +    </mat-dialog-content>
в этой части проблема: если имя и должность короткие, то название департамента смещается влево, нужно, чтобы всё ровненько в своих столбцах было

2021-10-07 18:45 UTC, tsinevik commented on src/app/shared/modals/add-employee/add-employee.component.scss
> +
не используется, нужно убрать

2021-10-07 18:45 UTC, tsinevik commented on src/app/shared/modals/add-employee/add-employee.component.scss
> +}
ширина модалки задаётся через конфиг в сервисе MatDialog

2021-10-07 18:45 UTC, tsinevik commented on src/app/shared/modals/add-employee/add-employee.component.scss
> +	}
не используется

2021-10-07 18:45 UTC, tsinevik commented on src/app/shared/modals/add-employee/add-employee.component.html
> +    </mat-dialog-content>
По макету между пользователями есть разделительная линии, попробуй сделать её с помощью mat-divider'а

2021-10-07 18:56 UTC, Randattt commented on src/app/shared/modals/add-employee/add-employee.component.scss
> +	}
Иначе иконка слишком высоко, относительно инпута. Добавлю в .search тогда еще align-items)

2021-10-08 12:02 UTC, tsinevik commented on src/app/shared/modals/add-employee/add-employee.component.scss
> +	}
использовать position: absolute такое себе, как минимум, у тебя названия департаментов выровнены по правому краю, что не есть хорошо. Также при маленьком экране название может на нижнюю строчку уйти. В таких вещах вообще лучше не выбивать из общего потока элементы, это ни к чему.
Либо попробуй флексы как-то грамотно использовать (с помощью flex-basis задать примерные размеры ячеек?), либо гриды

2021-10-08 14:28 UTC, tsinevik commented on src/app/shared/modals/add-employee/add-employee.component.scss
> +		text-align: right;
Попробуй сделать данные разных длин (длинные и короткие имена, позиции и департаменты) и посмотри, как это выглядит. И мб я неправильно сформулировал прошлый комментарий, нужно выравнивание по левой стороне, а не правой.

2021-10-11 09:24 UTC, merged