Input number mask
LT-Students/DigitalOffice-frontend pull request #260
Opened 2021-10-26 17:57 UTC by Randattt

2021-10-29 20:54 UTC, Dimokku reviewed
Ещё нельзя ввести '+' перед вводом номера

2021-10-29 20:54 UTC, Dimokku commented on src/app/shared/component/phone-input/phone-input.component.html
> +	[placeholder]="'Введите номер в международном формате'"
Т.к. do-phone-input ведёт себя по факту как контрол, и у тебя есть реализация placeholder в нём, я предлагаю передавать значение плейсхолдера как атрибут в do-phone-input, и использовать в do-phone-input эту переменную

2021-10-29 20:54 UTC, Dimokku commented on src/app/modules/employee/components/main-info/communications/edit-contact/edit-contact.component.html
> +		<do-phone-input [formControl]="control"></do-phone-input>
И тут тоже передать плейсхолдер

2021-10-29 20:54 UTC, Dimokku commented on src/app/modules/employee/components/main-info/communications/add-contact/add-contact.component.html
> +			<do-phone-input formControlName="value"></do-phone-input>
Вот здесь передать placeholder

2021-10-29 20:54 UTC, Dimokku commented on src/app/shared/component/phone-input/phone-input.component.ts
> +import { Observable, Subject } from 'rxjs';
Observable не используется, уд0ли импорт

2021-10-29 20:54 UTC, Dimokku commented on src/app/shared/component/phone-input/phone-input.component.ts
> +	public control: FormControl;
Перемести переменную выше конструктора

2021-10-29 20:54 UTC, Dimokku commented on src/app/shared/shared.module.ts
> -import { LoadingBarRouterModule } from '@ngx-loading-bar/router';
Этот импорт не использовался?

2021-11-01 10:35 UTC, Randattt commented on src/app/shared/shared.module.ts
> -import { LoadingBarRouterModule } from '@ngx-loading-bar/router';
+

2021-11-01 13:46 UTC, Randattt commented on src/app/shared/component/phone-input/phone-input.component.ts
> +		this.control = this._fb.control('hello', CommunicationTypeModel.getValidatorsByType(CommunicationType.Phone));
Проверка была)))

2021-11-01 23:38 UTC, tsinevik requested changes

2021-11-01 23:38 UTC, tsinevik commented on src/app/shared/component/phone-input/phone-input.component.ts
> +		if (pasted && /\D/g.test(pasted?.getData('text') ?? '')) {
Не понял, ты сначала проверяешь, что pasted не является falsy-значением, а потом в правой части всё равно используешь операторы ? и ??, хотя pasted в этом месте у нас уже никогда не будут null или undefined

2021-11-01 23:38 UTC, tsinevik commented on src/app/modules/employee/components/main-info/communications/add-contact/add-contact.component.html
> +			*ngIf="contactForm.controls['type'].value !== 'Phone'; else phoneInput"
Тут лучше енамку использовать

2021-11-01 23:38 UTC, tsinevik commented on src/app/modules/employee/components/main-info/communications/edit-contact/edit-contact.component.html
> +		*ngIf="dialogData.type !== 'Phone'; else phoneInput"
Я посмотрел классы компонент, связанных с коммуникейшн и нигде не используется енамка для контактов, везде строка. Нужно заменить на енамку. Обсудите с Димой, будете ли вы это делать в рамках этой задачи или в отдельную вынесете.

2021-11-01 23:38 UTC, tsinevik commented on src/app/shared/component/phone-input/phone-input.component.html
> +	(keydown.backspace)="OnPhoneKeyDown()"
camelCase

2021-11-01 23:38 UTC, tsinevik commented on src/app/shared/component/phone-input/phone-input.component.html
> +	(keydown.backspace)="OnPhoneKeyDown()"
По названию функции можно предположить, что она обрабатывает все нажатия кнопок, а не только бэкспейс

2021-11-01 23:38 UTC, tsinevik commented on src/app/shared/component/phone-input/phone-input.component.html
> +	(keydown.backspace)="OnPhoneKeyDown()"
Мне кажется, префикс Phone лишний и он только зря удлиняет название функции. Из названия компоненты и так понятно, что мы с инпутом для телефона взаимодействуем.

2021-11-01 23:38 UTC, tsinevik commented on src/app/shared/component/phone-input/phone-input.component.ts
> +		}
Кек, дважды повторяется присвоение ?valueAccessor

2021-11-01 23:38 UTC, tsinevik commented on src/app/shared/component/phone-input/phone-input.component.ts
> +		this.id = `custom-phone-input-id-${this.control.value}`;
`this.control.value` при инициализации компонента всегда равно пустой строке, т.е ты нескольким инпутам будешь один и тот же айди назначать.
Нужно завести в классе статическую переменную со смыслом idCounter или типа того, которая будет увеличиваться на один с каждым присвоением

2021-11-01 23:38 UTC, tsinevik commented on src/app/shared/component/phone-input/phone-input.component.ts
> +		this.ngControl = null;
Не понял, зачем ты тут null назначаешь?

2021-11-01 23:42 UTC, Dimokku commented on src/app/shared/component/phone-input/phone-input.component.ts
> +		if (pasted && /\D/g.test(pasted?.getData('text') ?? '')) {
Упс, это я такую фигню посоветовал. Рома прав

2021-11-02 11:35 UTC, tsinevik requested changes

2021-11-02 11:35 UTC, tsinevik commented on src/app/shared/component/phone-input/phone-input.component.ts
> +	public OnBackspaceDown(): void {
всё ещё не camelCase

2021-11-02 11:35 UTC, tsinevik commented on src/app/shared/component/phone-input/phone-input.component.ts
> +		if (/\D/g.test(pasted?.getData('text') ?? '')) {
Я в комментарии имел в виду сделать так: `if (pasted && /\D/g.test(pasted.getData(...))) {}`
Тогда если `pasted === null`, то проверка на регулярку не будет проводится. А в твоём случае, даже если pasted === null, то ты тестируешь пустую строку, что является лишним действием.
Хотя по факту это мелочь и на производительности роли никакой не сыграет.

2021-11-02 11:35 UTC, tsinevik commented on src/app/shared/component/phone-input/phone-input.component.ts
> +		}
А разве после этого действия функция не должна прекратиться? Дальше по условиям же пойдет выполнение кода

2021-11-02 11:35 UTC, tsinevik commented on src/app/shared/component/phone-input/phone-input.component.ts
> +		let selectionStart: number | null = (e.target as HTMLInputElement).selectionStart;
const

2021-11-02 11:35 UTC, tsinevik commented on src/app/shared/component/phone-input/phone-input.component.ts
> +				inputNumbersValue = '7' + inputNumbersValue;
Т.е. если у пользователя код страны будет начинаться с 8 или 9, то он не сможет набрать свой номер?

2021-11-02 17:18 UTC, tsinevik submitted a review, later dismissed

2021-11-02 19:39 UTC, Dimokku approved these changes

2021-11-02 20:55 UTC, merged