Feature/filtering users status
LT-Students/DigitalOffice-frontend pull request #262
Opened 2021-10-28 15:59 UTC by maxtalanov

Работа с фильтром статусов

2021-11-17 14:21 UTC, Dimokku commented on src/app/modules/admin/components/manage-users/manage-users.component.ts
> +				.subscribe((params) => {});
Ну и приходит туда не params, а response (это чисто прикопка к именованию параметра), то есть тебе бы ещё как и в onAddEmployeeClick проверять статус операции

2021-11-17 14:39 UTC, maxtalanov commented on src/app/modules/admin/components/manage-users/manage-users.component.ts
>  import { NewEmployeeComponent } from '../../modals/new-employee/new-employee.component';
Исправлен

2021-11-17 16:25 UTC, tsinevik requested changes

2021-11-17 16:25 UTC, tsinevik commented on src/app/modules/admin/components/manage-users/manage-users.component.ts
> +	@ViewChild('paginator') paginator: MatPaginator | undefined;
можно вот так оформить без переменной в темплейте
`@ViewChild(MatPaginator) paginator?: MatPaginator;`

2021-11-17 16:25 UTC, tsinevik commented on src/app/modules/admin/components/manage-users/manage-users.component.ts
> +	private _refreshCurrentPage$$: Subject<any>;
не any, можно на void заменить

2021-11-17 16:25 UTC, tsinevik commented on src/app/modules/admin/components/manage-users/manage-users.component.ts
> +					}
лишняя проверка, ты уже выше проверил, что пагинатор существует

2021-11-17 16:25 UTC, tsinevik commented on src/app/modules/admin/components/manage-users/manage-users.component.ts
> +	public getUsers(filters: any, event: PageEvent | null): Observable<OperationResultResponse<UserInfo[]>> {
filters все же не any

2021-11-17 16:25 UTC, tsinevik commented on src/app/modules/admin/components/manage-users/manage-users.component.html
> +				<mat-option value="all">Все</mat-option>
мне кажется, здесь можно заменить на true и false, чтобы лишнюю проверку не делать, т.к. у нас по сути поле `includedeactivated` принимает булево значение. Или же мб более понятный и дескриптивный вариант будет завести енамку Status с опциями ACTIVE и ALL, у которых будут значения true и false.

2021-11-18 13:31 UTC, maxtalanov commented on src/app/modules/admin/components/manage-users/manage-users.component.ts
> +					}
Приняли решение с Ромой оставить как есть на данный момент

2021-11-19 14:08 UTC, Dimokku approved these changes

2021-11-19 14:14 UTC, merged