Improvement/add button archive
LT-Students/DigitalOffice-frontend pull request #264
Opened 2021-10-29 15:18 UTC by Evgenia1394

2021-11-01 14:29 UTC, Dimokku reviewed
И ещё у кнопки не на одном уровне текст и значок, и маргин какой-то большой до основной информации

2021-11-01 14:29 UTC, Dimokku commented on src/app/modules/employee/employee-page.component.html
> +					<div (click)="onDeleteEmployeeClick(selectedUser.id)">
Предлагаю убрать <ng-container *ngIf="selectedUser.id as userId">, а в onDeleteEmployeeClick добавить ещё возможный тип как undefined, и уже в самой функции делать проверку на существование значения

2021-11-01 14:29 UTC, Dimokku commented on src/app/modules/employee/employee-page.component.html
> +					<div (click)="onRestoreEmployeeClick(selectedUser.id)">
И в этой функции аналогично onDeleteEmployeeClick

2021-11-01 14:29 UTC, Dimokku commented on src/app/modules/employee/employee-page.component.ts
>  	private _unsubscribe$: Subject<void>;
У нас теперь в проекте новое правило по именованию Subject'ов и Observable'ов - к первым добавляем два знака $, ко вторым один, то есть _unsubscribe$$

2021-11-01 14:29 UTC, Dimokku commented on src/app/modules/employee/employee-page.component.ts
> +				switchMap((confirm) => (confirm ? this._userService.disableUser(userId) : EMPTY)),
Вместо тернарного оператора используй rxjs оператор iif

2021-11-01 14:29 UTC, Dimokku commented on src/app/modules/employee/employee-page.component.ts
> +				switchMap((confirm) => (confirm ? this._userService.activateUser(userId) : EMPTY)),
iif

2021-11-01 14:29 UTC, Dimokku commented on src/app/core/models/user/personal-info-manager.ts
> +	constructor(public _user: UserInfo | undefined) {}
Почему public?

2021-11-01 22:56 UTC, tsinevik requested changes

2021-11-01 22:56 UTC, tsinevik commented on src/app/modules/employee/employee-page.component.html
> +	></do-breadcrumbs>
Раз уж начала делать, то надо идти до победного и добавить в конец ещё ссылку на страницу пользователя, на который мы находимся, как на макетах

2021-11-01 22:56 UTC, tsinevik commented on src/app/modules/employee/employee-page.component.ts
> +		this.userLogged$ = this._currentUserService.user$.pipe(map((item) => item.isAdmin));
Всё же не абстрактный item приходит, а юзер

2021-11-01 22:56 UTC, tsinevik commented on src/app/modules/employee/employee-page.component.ts
> +	onRestoreEmployeeClick(userId: string | undefined) {
Модификатор и возвращаемый тип

2021-11-01 22:56 UTC, tsinevik commented on src/app/modules/employee/employee-page.component.ts
>  	}
Эти две функции почти полностью дублируют код, подумай, как его можно сократить до одного вызова. Или спроси у Димы.

2021-11-09 14:50 UTC, Dimokku approved these changes

2021-11-10 12:36 UTC, Dimokku approved these changes

2021-11-11 14:17 UTC, tsinevik approved these changes

2021-11-11 14:30 UTC, merged