SnackBar for services
LT-Students/DigitalOffice-frontend pull request #267
Opened 2021-11-03 15:12 UTC by Randattt

2021-11-08 13:13 UTC, Dimokku reviewed
Также snackbar остался в new-employee.component.ts, перенеси в UserService, и проверь, что сообщение об ошибке не пустое

2021-11-08 13:13 UTC, Dimokku commented on src/app/modules/admin/components/dashboard/dashboard.component.ts
> +	constructor(private _router: Router, public dialog: MatDialog, public modalService: ModalService) {
Из импортов удали неиспользуемый импорт MatSnackBar

2021-11-08 13:13 UTC, Dimokku commented on src/app/modules/admin/components/new-project/new-project.component.ts
> -		private _snackBar: MatSnackBar,
Из импортов тоже удалить

2021-11-08 13:13 UTC, Dimokku commented on src/app/modules/admin/modals/new-department/new-department.component.ts
> -		private _snackBar: MatSnackBar,
Удалить из импортов

2021-11-08 13:13 UTC, Dimokku commented on src/app/modules/admin/modals/new-office/new-office.component.ts
> -		private _snackBar: MatSnackBar,
Удалить из импортов

2021-11-08 13:13 UTC, Dimokku commented on src/app/modules/admin/modals/new-position/new-position.component.ts
> -		private _snackBar: MatSnackBar,
Удалить из импортов

2021-11-08 13:13 UTC, Dimokku commented on src/app/modules/admin/modals/new-role/new-role.component.ts
> -		private _snackBar: MatSnackBar
Удалить из импортов

2021-11-08 13:13 UTC, Dimokku commented on src/app/modules/employee/components/main-info/communications/add-contact/add-contact.component.ts
> -		private _snackBar: MatSnackBar
Удалить из импортов

2021-11-08 13:13 UTC, Dimokku commented on src/app/modules/employee/components/main-info/communications/edit-contact/edit-contact.component.ts
> -		private _snackBar: MatSnackBar
Удалить из импортов

2021-11-08 13:13 UTC, Dimokku commented on src/app/modules/employee/components/main-info/main-info.component.ts
> -		private _snackBar: MatSnackBar,
Импорты

2021-11-08 13:13 UTC, Dimokku commented on src/app/modules/employee/employee-page.component.ts
> -		private _snackBar: MatSnackBar,
Импорты

2021-11-08 13:13 UTC, Dimokku commented on src/app/modules/news/components/news-feed/news-feed.component.ts
> -		private _snackBar: MatSnackBar,
Импорты

2021-11-12 14:55 UTC, Dimokku commented on src/app/core/models/response/response-message.model.ts
> +		let result = this._errorMessageTypes.find((item) => item.triggered === triggeredFrom);
Таки const

2021-11-12 14:55 UTC, Dimokku commented on src/app/core/models/response/response-message.model.ts
> +		let errorMessage: string = err.error.errors?.[0] ?? 'Что-то пошло не так :(';
Как я узнал, сообщений в errors может быть несколько, поэтому надо подумать, как объединить их все в одно сообщение

2021-11-12 14:55 UTC, Dimokku commented on src/app/core/models/response/response-message.model.ts
> +	public static getSuccessMessage(triggeredFrom: MessageTriggeredFrom, method: MessageMethod) {
Надо ещё рассмотреть случаи с кодом 200/201 и статусом PartialSuccess

2021-11-17 12:28 UTC, Dimokku commented on src/app/core/services/company/office.service.ts
> +		@Inject(ResponseMessageModel) private _responseMessage: ResponseMessageModel
Разве "@Inject(ResponseMessageModel)" здесь нужен?

2021-11-17 12:28 UTC, Dimokku commented on src/app/core/models/response/response-message.model.ts
> +	public getSuccessMessage(triggeredFrom: MessageTriggeredFrom, method: MessageMethod, success: any): string {
Лучше передавать success: string вместо success: any, так будет более понятно (в других местах тоже)

2021-11-17 12:28 UTC, Dimokku commented on src/app/core/models/response/response-message.model.ts
> +	public showSuccessMessage(triggeredFrom: MessageTriggeredFrom, method: MessageMethod, success: any): void {
string

2021-11-17 12:28 UTC, Dimokku commented on src/app/core/services/department/department.service.ts
> +		@Inject(ResponseMessageModel) private _responseMessage: ResponseMessageModel
И тут

2021-11-17 12:28 UTC, Dimokku commented on src/app/core/services/employee-page.service.ts
> +		@Inject(ResponseMessageModel) private _responseMessage: ResponseMessageModel
И тут

2021-11-17 12:28 UTC, Dimokku commented on src/app/core/services/news/news.service.ts
> +		@Inject(ResponseMessageModel) private _responseMessage: ResponseMessageModel
Ну и все остальные сервисы...

2021-11-17 12:28 UTC, Dimokku commented on src/app/core/services/user/communication.service.ts
> +		private _snackBar: MatSnackBar,
Забыл убрать?

2021-11-17 12:35 UTC, Randattt commented on src/app/core/services/user/communication.service.ts
> +		private _snackBar: MatSnackBar,
+

2021-11-17 12:43 UTC, Randattt commented on src/app/core/models/response/response-message.model.ts
> +	public getSuccessMessage(triggeredFrom: MessageTriggeredFrom, method: MessageMethod, success: any): string {
Это не string

2021-11-17 13:40 UTC, Dimokku submitted a review, later dismissed

2021-11-17 13:59 UTC, tsinevik requested changes

2021-11-17 13:59 UTC, tsinevik commented on src/app/core/models/response/response-message.model.ts
> +		return successMessage;
Условие нужно в самый верх функции перенести, в твоём случае ты инициализируешь сначала две переменные, а потом делаешь проверку и в случае успеха ты эти значения в этих переменных не используешь.
Переменная `successMessage` не нужна. Можно просто возвращать строку.

2021-11-17 13:59 UTC, tsinevik commented on src/app/core/models/response/response-message.model.ts
> +		}
Здесь то же самое, в случае успеха условия ты зря выполнял прошлые операции

2021-11-17 13:59 UTC, tsinevik commented on src/app/core/models/response/response-message.model.ts
> +	public getErrorMessage(err: any): string {
это, по идее, не any, а HttpErrorResponse (или как-то так тип называется для ошибок хттп запросов)

2021-11-17 13:59 UTC, tsinevik commented on src/app/core/models/response/response-message.model.ts
>  		}
И тут нужно сначала условия писать

2021-11-17 13:59 UTC, tsinevik commented on src/app/core/models/response/response-message.model.ts
> +	public showErrorMessage(err: any): void {
не any

2021-11-17 13:59 UTC, tsinevik commented on src/app/core/models/response/response-message.model.ts
> +		}
То же самое

2021-11-17 13:59 UTC, tsinevik commented on src/app/core/models/response/response-message.model.ts
> +				})
Тут, конечно, не прям обязаловка, но я бы переделал эти функции в чистые, чтобы они возвращали строки, а сами снэкбары в catchError и tap прописал

2021-11-17 13:59 UTC, tsinevik commented on src/app/core/models/response/response-message.model.ts
> +	public message(triggeredFrom: MessageTriggeredFrom, method: MessageMethod) {
возвращаемый тип

2021-11-17 13:59 UTC, tsinevik commented on src/app/core/models/response/response-message.model.ts
> +			return source.pipe(
то ли я что-то не понял, то ли непонятная дичь тут происходит. Почему просто функцию pipe с нужными операторами не вернуть?
Типа такого
`return pipe(
      catchError(),
      tap()
`

2021-11-17 20:05 UTC, tsinevik approved these changes

2021-11-17 21:21 UTC, Dimokku approved these changes

2021-11-17 21:21 UTC, merged