Improvement/split add hours into two components
LT-Students/DigitalOffice-frontend pull request #278
Opened 2021-11-22 01:51 UTC by Dimokku

2021-11-22 08:57 UTC, tsinevik requested changes

2021-11-22 08:57 UTC, tsinevik commented on src/app/core/services/attendance.service.ts
> +		return this._timeDurationService.getDuration(datePeriod, 8 * 0.5, this.disableWeekends);
Оооочень плохое решение, не делай так, об этом легко забыть и потом снова придется фиксить. Лучше при присваивании ставки проверяй, что она существует и если нет, то присваивай какое-то дефолтное значение. Когда бэк починит ставку, у нас всё продолжит работать, как надо.

И вообще иметь дефолтную ставку, наверное, неплохой вариант, правда, вопрос в том, какой она должна быть. Я в конструкторе ставил единицу, но мб можно и какую-то другую поставить.

2021-11-22 08:57 UTC, tsinevik commented on src/app/modules/user/components/add-hours/add-hours.component.html
> +	<ng-container *ngIf="isProjectForm; else leaveTimeForm">
Так себе решение, лучше вынести в родительский компонент это условие. Потому что в данном случае если мы выбираем внесение в отсутствие, то у нас грузится новый компонент, но при этом этот компонент продолжает жизнь и информация, которая в нём хранилась, также остается, т.е. мы продолжаем хранить ненужные нам данные, хотя компонент уже никак не используется.

2021-11-22 08:57 UTC, tsinevik commented on src/app/modules/user/components/add-hours/add-hours.component.ts
> +		//this.recommendedTime.next(0);
Почему бы не удалить, если не используется?

2021-11-22 08:57 UTC, tsinevik commented on src/app/modules/user/components/add-hours/add-leave-hours/add-leave-hours.component.ts
> +			});
???

2021-11-22 14:16 UTC, Dimokku commented on src/app/core/services/attendance.service.ts
> +		return this._timeDurationService.getDuration(datePeriod, 8 * 0.5, this.disableWeekends);
Думаю, дефолтная единичка оптимальный вариант

2021-11-23 14:27 UTC, tsinevik requested changes

2021-11-23 20:35 UTC, Dimokku commented on src/app/core/services/attendance.service.ts
> +	public setUserIdAndRate(rate: number, userId?: string): void {
![image](https://user-images.githubusercontent.com/32371247/143103056-d409d167-d4b3-4e10-aed7-5c4c1d7dd4b1.png)

2021-11-23 20:36 UTC, Dimokku commented on src/app/core/services/attendance.service.ts
> +	public setUserIdAndRate(rate: number, userId?: string): void {
![image](https://user-images.githubusercontent.com/32371247/143103445-0e727260-f67a-4847-bcdd-e2a17d465351.png)

2021-11-23 20:36 UTC, Dimokku commented on src/app/modules/user/components/add-hours/add-hours.component.ts
>  	}
Да, формы переключаются, часы вносятся

2021-11-23 23:34 UTC, tsinevik submitted a review, later dismissed

2021-11-23 23:34 UTC, tsinevik commented on src/app/core/services/attendance.service.ts
> +	public setUserIdAndRate(rate: number, userId: string): void {
Поменяй аргументы местами

2021-11-23 23:37 UTC, tsinevik approved these changes

2021-11-23 23:43 UTC, merged