refactoring(employee-page): update element page
LT-Students/DigitalOffice-frontend pull request #344
Opened 2022-03-01 20:36 UTC by maxtalanov

[Макет: **КАРТОЧКА ПОЛЬЗОВАТЕЛЯ**](https://www.figma.com/file/CQWlWy0slBw9Iqo6mPJtfM/%D0%A6%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%BE%D0%B9-%D0%BE%D1%84%D0%B8%D1%81?node-id=17229%3A34814f)
Чек-лист (этапы обновления):

2022-03-05 11:25 UTC, tsinevik requested changes

2022-03-05 11:25 UTC, tsinevik commented on src/app/shared/component/content-container/content-container.component.scss
> +		padding: 56px 0 0 0;
эээм, зачем?

2022-03-05 11:27 UTC, tsinevik commented on src/app/modules/employee/employee-page.component.html
> +				<mat-icon class="employee-page__button-icon">restore_from_trash</mat-icon>
иконка не соответствует макету

2022-03-05 11:28 UTC, tsinevik commented on src/app/modules/employee/employee-page.component.html
> +			<mat-icon class="employee-page__button-icon">archive</mat-icon>
иконка не соответствует макету

2022-03-05 11:34 UTC, tsinevik commented on src/app/modules/employee/employee-page.component.scss
> +		color: #9d9d9d;
для цветов используй переменные из файла stylesheets/base/variables

2022-03-05 11:34 UTC, tsinevik commented on src/app/modules/employee/employee-page.component.scss
> +		min-height: 36px;
стёр эти изменения и разницы не заметил, для чего это?

2022-03-06 09:53 UTC, maxtalanov commented on src/app/shared/component/content-container/content-container.component.scss
> +		padding: 56px 0 0 0;
@tsinevik в следующим коммите будет исправление. Будет только у верхнего  56px padding

2022-03-06 12:12 UTC, maxtalanov commented on src/app/modules/employee/employee-page.component.html
> +				<mat-icon class="employee-page__button-icon">restore_from_trash</mat-icon>
@tsinevik обновил

2022-03-07 12:25 UTC, tsinevik requested changes
В package-lock.json какая-то дичь происходит, что ты делал с этим файлом?

2022-03-07 12:25 UTC, tsinevik commented on src/app/modules/employee/employee-page.component.html
> +                    <img class='cell__btn-img' src='../assets/svg/employee-page/unzip.svg' alt='иконка востановления' />
Тут две иконки выводится

2022-03-07 12:25 UTC, tsinevik commented on src/assets/svg/employee-page/archive.svg
> +</svg>
Обе иконки есть в материале, не нужно для них создавать отдельный файлы. Чтобы использовать outline версии, нужно в index.html заменить импорт материал иконок на следующее:
`<link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet" />`

А чтобы в самой хтмл использовать outline иконоки, пишем так:
`<mat-icon fontSet="material-icons-outlined>icon_name</mat-icon>"`

2022-03-07 12:25 UTC, tsinevik commented on src/app/modules/employee/components/competences/competences.component.html
> +            <h2 underlinedSize='sm' doUnderline>Сертификатыё</h2>
Старайся перепроверять тексты на опечатки

2022-03-09 10:11 UTC, tsinevik requested changes

2022-03-09 10:11 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.scss
> +}
какой-то очень странный класс

2022-03-09 10:11 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.scss
> +	&__container {}
не используется

2022-03-09 10:11 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.scss
> +		$body-2: mat.define-typography-level(13px, 18px, 400);
а ты вообще проверил, что это работает? Потому что шрифты от этой записи не поменялись. Потому что ты здесь объявляешь переменную body-2 и никак не используешь.

Тебе нужно пойти в theme.scss, найти custom-typography и в ней переопределить стиль body-2. После чего он автоматически будет применяться ко всем элементам с классом mat-body-2

2022-03-09 10:11 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.scss
> +		$body-2: mat.define-typography-level(13px, 19px, 400);
здесь то же самое

2022-03-09 10:11 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.scss
> +	}
не используется

2022-03-09 11:45 UTC, maxtalanov commented on src/app/modules/employee/components/main-info/communications/communications.component.html
> +                    (click)='onDeleteClick(communication, $event)'
Web Shtorm

2022-03-09 11:47 UTC, maxtalanov commented on src/app/modules/employee/components/main-info/main-info.component.html
> +                                <p class="general-data__tab-par">Женщина</p>
Paragraph и table

2022-03-09 11:48 UTC, maxtalanov commented on src/app/modules/employee/components/main-info/main-info.component.scss
> +}
Это обнуление стилей кнопки

2022-03-09 15:50 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.scss
> +}
Посмотрел по фигме: т.к. материал не предлагает нам такого вида кнопки, то лучше сделать мб отдельный глобальный класс или компонент/директиву, который будет превращать кнопку в нужные нам вид. И ты в любом случае не учёл здесь состояния hover и focus.

2022-03-09 15:50 UTC, tsinevik commented on src/app/modules/employee/components/main-info/communications/communications.component.html
> +                    (click)='onDeleteClick(communication, $event)'
а заливаешь как в репозиторий файлы?

2022-03-09 15:55 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.html
> +                                <p class="general-data__tab-par">Женщина</p>
так себе названия. Во-первых, по этим сокращениям не очень понятно, что кроется за ними: tab – это само по себе слово, которое обозначает "вкладка", par просто с толку сбивает. Во-вторых, у нас всё же тут не таблица, поэтому table здесь не особо подходит, а класс параграф ты вообще никак не используешь, поэтому от него тоже можно спокойно избавиться.

2022-03-09 16:11 UTC, maxtalanov commented on src/app/modules/employee/components/main-info/communications/communications.component.html
> +                    (click)='onDeleteClick(communication, $event)'
Через встроенный модуль git , реже  через консоль

2022-03-09 18:22 UTC, maxtalanov commented on src/app/modules/employee/components/main-info/main-info.component.scss
> +}
@tsinevik окей

2022-03-17 09:26 UTC, closed without merging