Changed general info employee card.
LT-Students/DigitalOffice-frontend pull request #358
Opened 2022-03-29 14:45 UTC by zimbara14

2022-03-29 17:04 UTC, tsinevik requested changes
1. Также нужно удалить весь `<ng-template #editForm>`, потому что он больше не используется
2. Не могу в нужном месте комментарий оставить, поэтому тут пишу: есть проблема с блоком `<q ...> {{ user?.about }} </q>`. Можешь зайти на страницу управления сотрудниками, выбрать первого пользователя (Прохор Прохоров) и ты увидишь, что у него этот блок растянулся на всю страницу из-за чего основную информацию не видно.

2022-03-29 18:51 UTC, tsinevik reviewed
А, ещё забыл добавить, мы должны выводить статус пользователя после имени в виде эмодзи. Сейчас там енамка как строка выводится. Можешь для этого также пайп сделать, который бы конвертировал статус в эмодзи. Посмотри `core/models/time/leave-type.model.ts`, можно использовать этот класс внутри пайпа, чтобы получить соотвествующий эмодзи

2022-04-06 15:17 UTC, tsinevik requested changes

2022-04-06 15:17 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.html
>  							[matTooltip]="user.firstName + ' ' + (user.status | lowercase)"
Сейчас при наведении курсора на эмодзи выводится тултип с английским названием статуса. Используй здесь пайп `userStatus`, но измени его так, чтобы он мог ещё выводить помимо эмодзи статус на русском.

2022-04-06 15:17 UTC, tsinevik commented on src/app/shared/pipes/user-status.pipe.ts
> +			return `${emoji ? userModel?.emojiIcon : ''}`;
Вот здесь, если параметр `label = true`, нужно вывести `userModel.statusInRussian`

2022-04-06 15:17 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.scss
> +		overflow: scroll;
не очень понимаю, зачем скролл на имени?

2022-04-06 15:17 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.scss
> +		transition: visibility 1s ease-in;
Во-первых, это нужно перенести в `__upload-button`, т.к. мы изменяем состояние кнопки, а не аватара.
Во-вторых, у нас должна не просто исчезать и появляться кнопка, а должна выезжать снизу, для этого тебе нужно не `visibility` слушать, а `bottom`. `bottom` изначально должен быть внизу, а на `hover` выезжать вверх. И замени 1 секунду на 0.1, а то слишком долго получается.

2022-04-06 15:17 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.scss
> +
И это соотвественно убрать/поменять на bottom

2022-04-08 12:12 UTC, zimbara14 commented on src/app/modules/employee/components/main-info/main-info.component.scss
> +		overflow: scroll;
Я добавила это потому что если пользователь указывает слишком длинное имя, часть Общие сведения уйдёт направо и не будет видно. Мне убрать?

2022-04-08 16:08 UTC, tsinevik commented on src/app/shared/pipes/full-name.pipe.ts
> +		return `${user.firstName} ${middleName ? user.middleName : ''} ${user.lastName}`;
помимо флага `middleName` проверяй ещё, что у самого юзера он есть. И, как я понимаю, если у пользователя нет отчества, хотя мы хотим его указать, то у нас лишний пробел между именем и фамилией появится
Т.е. так
```
return `${user.firstName} ${middleName && user?.middleName ? user.middleName : ' '}${user.lastName}`;
```

2022-04-08 18:08 UTC, merged