update template for projects card
LT-Students/DigitalOffice-frontend pull request #359
Opened 2022-03-30 15:46 UTC by kohuro

2022-03-30 18:24 UTC, tsinevik requested changes

2022-03-30 18:24 UTC, tsinevik commented on src/app/modules/employee/components/projects/projects.component.html
> +					<h4 class="projects-table__project-name">{{ project.name }}</h4>
На макетах используется заголовок h5

2022-03-30 18:24 UTC, tsinevik commented on src/app/modules/employee/components/projects/projects.component.html
> +					<p class="projects-table__label">{{ project.status }}</p>
Мелочь, но лучше вместо label написать status или status-label, потому что само слово label не несёт того смысла, который у нас в этом элементе заложен.

2022-03-30 18:24 UTC, tsinevik commented on src/app/modules/employee/components/projects/projects.component.html
> +						C <span>{{ project.startedAt }}</span>
Странно выглядит, почему ты решила обернуть `project.startedAt` в `span`? Можно написать `С {{ project.startedAt }}`, ни к чему новые элементы создавать

2022-03-30 18:24 UTC, tsinevik commented on src/app/modules/employee/components/projects/projects.component.html
> +						C <span>{{ project.startedAt }}</span>
А также у нас почему-то в принципе нет поля `startedAt`, уточню у бэкэнда. В нём, по идее, должна дата прийти, которую нужно было бы через пайп date обработать.

2022-04-12 15:03 UTC, tsinevik requested changes

2022-04-12 15:03 UTC, tsinevik commented on src/app/shared/directives/tooltip.directive.ts
> +		let client = this.el.nativeElement.clientHeight;
`let` используем только тогда, когда переменная меняет значение, во всех остальных случаях используем `const`. Вообще за правило возьми, что сначала пишем `const` и только потом, если понимаешь, что без переприсваивания значения не обойтись, то пишем `let`.

2022-04-14 08:01 UTC, kohuro commented on src/app/modules/employee/components/projects/projects.component.html
> +				<span class="mat-h4 primary">{{ section.projects.length | i18nPlural: section.plural }}</span>
Чтобы количество проектов было акцентным цветом. Без него заголовок целиком чёрный

2022-04-14 09:13 UTC, tsinevik commented on src/app/modules/employee/components/projects/projects.component.html
> +				<span class="mat-h4 primary">{{ section.projects.length | i18nPlural: section.plural }}</span>
а, да, действительно, затупил

2022-04-15 09:55 UTC, tsinevik approved these changes

2022-04-15 09:55 UTC, merged