Old variables replaced
LT-Students/DigitalOffice-frontend pull request #366
Opened 2022-04-18 20:10 UTC by kohuro

2022-04-19 13:17 UTC, tsinevik requested changes
Ты много где оставила комментариев по сути чисто для меня – лучше так не делай. Пользы от них разработчикам 0, а место занимают + может сбить с толку кого-то. Комментарии нужно более грамотно использовать, описывать мб какие-то неочевидные функции, переменные, ещё что-то.

В принципе стирать их сейчас необязательно, потому что они по большей части были в компонентах, которые не используются, и эти компоненты, скорее всего, мы удалим.

2022-04-19 13:17 UTC, tsinevik commented on src/stylesheets/base/_variables.scss
> +// main_text в некоторых местах заменяет dark_2 и dark_4
Я так понимаю, это больше для меня комментарий. Удали, потому что остальным разработчикам не будет понятно, что это значит, т.к. этих двух цветов больше нет.

2022-04-19 13:17 UTC, tsinevik commented on src/stylesheets/base/_variables.scss
> +$heders: #263238;
Давай не будем брать опечатки из фигмы к нам, правильно `headers`

2022-04-19 13:17 UTC, tsinevik commented on src/stylesheets/base/_variables.scss
>  .light-gray-text {
Эти два класса нужно убрать, они у нас должны генерироваться выше. Убрать и заменить на сгенерированные.

2022-04-19 13:17 UTC, tsinevik commented on src/stylesheets/base/_variables.scss
>  );
Давай тут небольшое разделение сделаем: создадим два массива, один из которых будет содержать переменные с цветами для текстом, а другой с цветами для бэкграунда. И потом где идёт генерация классов, для классов текстов будем использовать массив с цветами текстов, а для бэкграунда – массив с цветами бэкграундов. Все остальные переменные можно не вносить в эти массивы (которые uncategorized, diagram, controls). Если вдруг нам какие-то классы с другими цветами понадобятся, то дополнительно будем вносить их соответствующие массивы.

2022-04-20 13:00 UTC, tsinevik commented on src/stylesheets/base/_variables.scss
> +	'bg_for_modals': #1b1511cc,
1. давай здесь оставим только переменные, которые непосредственно в фигме находятся в разделе **Bg**, остальные здесь вряд ли пригодятся.
2. давай мб уберем у названий приставку `bg_`, потому что у нас в таком случае генерируются классы `bg-bg_primary`, идёт странное дублирование bg.

2022-04-20 13:02 UTC, tsinevik commented on src/stylesheets/base/_variables.scss
>  	'light_4': #cecece,
Присваивай в качестве значений тут сами переменные, а не их значения. А то получается, если у нас изменится, например, `alert`, то нам нужно будет в двух местах поменять это значение.

2022-04-20 14:23 UTC, kohuro commented on src/stylesheets/base/_variables.scss
> +	'bg_for_modals': #1b1511cc,
Оставила тут bg и bg_2, так как они уже используются в некоторых местах

2022-04-20 15:44 UTC, tsinevik requested changes

2022-04-21 08:28 UTC, tsinevik approved these changes

2022-04-21 08:28 UTC, merged