Made a new dialog for editing data of employee card.
LT-Students/DigitalOffice-frontend pull request #367
Opened 2022-04-22 19:55 UTC by zimbara14

2022-04-23 21:19 UTC, tsinevik requested changes

2022-04-23 21:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		width: 650px;
1. этот параметр лучше передавать в конфиге модалки, т.е. `this.dialog.open(Component, { width: '650px' })`
2. У нас есть даже енамка ModalWidth, в которой прописаны возможные ширины модалок по нашим макетам
3. так-то по макетам ширина 672px, а не 650

2022-04-23 21:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		justify-content: space-evenly;
из-за этого свойства при включении редактирования верхушка первых двух инпутов уходит куда-то за границы контейнера

2022-04-23 21:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		}
delete

2022-04-23 21:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		justify-content: space-evenly;
эти свойства вроде бы никак не влияют на кнопку, тебе по факту только марджин нужен для отступа между иконкой и текстом

2022-04-23 21:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		}
материаловские классы лучше не использовать здесь

2022-04-23 21:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +	//}
delete

2022-04-23 21:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +	}
вот это всё очень какая-то странная штука

2022-04-23 21:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		grid-template-columns: 3fr 3fr;
`3fr 3fr` эквивалентно `1fr 1fr`

2022-04-23 21:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		flex-direction: column;
здесь лучше и проще использовать гриды, избавит сразу от многих проблем. У нас вся модалка по сути поделена на две колонки, можно спокойно сделать грид из двух колонок и это избавит нас от кучи дополнительных странных классов, которые ты ниже посоздавала.

Если нужно, чтобы какой-то элемент сразу на две колонки растягивался, то гриды позволяют такое делать.
Смотри этот гайд

https://css-tricks.com/snippets/css/complete-guide-grid/

2022-04-27 13:35 UTC, zimbara14 commented on src/app/modules/employee/modals/edit-info/edit-info.component.html
> +<!--</button>-->
Да, в макетах рядом с модалкой есть кнопка Х, я не знаю как ее можно поставить так, оставила коментарии чтобы спросить

<img width="851" alt="Screenshot 2022-04-27 at 16 35 02" src="https://user-images.githubusercontent.com/67017679/165530890-7d7f0b88-550f-4d93-9670-4920549eab96.png">

2022-04-29 11:20 UTC, zimbara14 commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		justify-content: space-evenly;
Решилось когда поменяла на grid

2022-04-29 11:22 UTC, zimbara14 commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +	}
Все удалила)

2022-04-29 11:50 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		justify-content: space-evenly;
Так это же edit-info__buttoN, а не buttonS

2022-04-29 11:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		justify-content: space-evenly;
а, это вообще ни тот, ни другой класс. Это `edit-info__edit-button`

2022-04-29 11:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		justify-content: space-evenly;
а, это вообще ни тот, ни другой класс. Это `edit-info__edit-button`

2022-04-29 13:33 UTC, zimbara14 commented on src/app/modules/employee/components/main-info/main-info.component.ts
> +		this.toggleEditMode(user);
она используется в других функциях, удалить эти функции тоже или как?

2022-04-29 13:36 UTC, zimbara14 commented on src/app/modules/employee/modals/edit-info/edit-info.component.ts
> +	isEditMode = false;
спасибо!! честно, не обращала внимание когда писала код, теперь знаю что надо)

2022-04-29 17:01 UTC, zimbara14 commented
есть несколько вопросов:
1. как нужно передавать данные, так чтобы они сохранялись для user? я думала что-то типо `dialogRef.afterClosed().subscribe((result) => {})` но не уверена
2. насколько понимаю, DoValidators.noWhitespace используется для того чтобы проверять есть ли пробелы в имени. их тогда не стоить применять?
3. уточняю, надо ли поменять все инпуты на новые (new ui kit)?
4. не до конца понимаю, как это сделать. нужно енамку создать?
<img width="216" alt="Screenshot 2022-04-29 at 19 55 47" src="https://user-images.githubusercontent.com/67017679/165989389-8835a144-1e5f-4f97-8832-78293be439fd.png">
5. для поля _Местоположение_ пока ничего не сделала, потому что нужно как-то использовать longitude и latitude, и в ТЗ описан какой-то механизм для выбора местоположения который не понимаю как надо сделать.

2022-04-30 09:12 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.ts
> +		this.toggleEditMode(user);
Пока что удали только её использование (и её саму)

2022-05-07 19:52 UTC, tsinevik requested changes
1. проверяй, чтобы отступы между элементами +- были похожи на те, что на макетах, а то местами сильно отличаются, например, кнопки находятся слишком близко к полю `about`
2. надеюсь, к среде всё-таки получится закрыть задачу. Но если вдруг ты всё пофиксишь быстро и будет ещё много времени, то можешь попробовать сделать отдельный компонент, который бы генерировал все поля с помощью `ngFor`, в котором мы бы итерировались по массиву, каждый элемент которого представляет конфиг, описывающий конкретное поле: лейбл, значение, режим редактирования и тд. Но это только если будет свободное время, т.к. в принципе не самая простая задача. А то действительно слишком много boilerplate выходит

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.ts
> +	}
или же две отдельные функции сделать для включения и выключения

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.ts
> +	}
как больше нравится

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.ts
> +	private userInfo?: InitialDataEditRequest<UserPath>;
назови переменную лучше так, чтобы было понятно, что это изначальное значение

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.html
> +            <mat-error *ngIf="editForm.controls['/FirstName']?.errors?.['whitespace']"
Ты для `formControlName` используешь енамку, но при этом для вывода ошибок обращаешь к этому контролу через строку, а не также через енамку

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.html
> +            <mat-error *ngIf="editForm.controls['/FirstName']?.errors?.['whitespace']"
Это касается всех полей

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.html
> +	<div class="edit-info__edit">
этот `div` и его класс не нужны. Они ни на что не влияют. Также при включении редактирования у нас пропадает кнопка, но сам `div` остается, просто он пустой

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/components/main-info/main-info.component.ts
> +			width: ModalWidth.L,
добавь сюда `autofocus: false`, чтобы кнопка редактирования не становилась сфокусированной

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +	}
delete

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		grid-template-columns: repeat(2, minmax(0, 1fr));
`minmax` тут в принципе ни к чему, ты можешь просто указать `repeat(2, 1fr)`, т.к. `1fr` и так в принципе до нуля может сжаться

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		column-gap: 25px;
По новым макетам `column-gap: 24px`, но это мелочь. Но также по макетам между строками тоже есть `gap`, который нужно использовать.

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		box-sizing: border-box;
все элементы по умолчанию имеют это свойство, ни к чему его явно указывать

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +	}
`margin` в данном случае лучше убрать, т.к. вместо него должно использоваться свойство `row-gap` у грида

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +		grid-column: 1;
никакого эффекта

2022-05-07 19:52 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.html
> +            <p class="edit-info__field-value">{{ user.lastName | placeholder }}</p>
не нужно в таких местах использовать тег `p`, он лишние марджины даёт, которые приходится переопределять. `p` семантически нужен для отображения абзацев в тексте, тут у нас нет абзаца.

2022-05-08 10:55 UTC, zimbara14 commented on src/app/modules/employee/modals/edit-info/edit-info.component.html
> +            >Фамилия не может состоять только из пробелов!
мм так было сделано в другой компоненте, оттуда взяла идею. как нужно исправить?

2022-05-10 16:55 UTC, zimbara14 commented on src/app/modules/employee/modals/edit-info/edit-info.component.ts
> +	constructor(@Inject(MAT_DIALOG_DATA) data: Required<User>,
потому что без `Required` не работало, но я удалила и теперь работает.

2022-05-10 16:56 UTC, zimbara14 commented on src/app/modules/employee/modals/edit-info/edit-info.component.ts
> +			})
что нужно сделать в случае ошибки?

2022-05-10 17:08 UTC, zimbara14 commented on src/app/modules/employee/modals/edit-info/edit-info.component.ts
> +		const { ...userInfo } = this.userInfo;
тут возникает проблема если попытаться передать `this.userInfo` потому что оно в начале пустое, а второй аргумент функции `createEditRequest()` не позволяет переменные undefined. 
<img width="1285" alt="Screenshot 2022-05-10 at 20 05 48" src="https://user-images.githubusercontent.com/67017679/167683859-34986f72-6724-4e43-9c95-a6b8eb2df274.png">

наверное решение это присвоить переменной `userInfo` что-то в начале, но не знаю что

2022-05-10 17:23 UTC, zimbara14 commented on src/app/modules/employee/modals/edit-info/edit-info.component.html
> +            <mat-error *ngIf="editForm.controls['/FirstName']?.errors?.['whitespace']"
<img width="618" alt="Screenshot 2022-05-10 at 20 21 56" src="https://user-images.githubusercontent.com/67017679/167686407-ac69f6d9-f7fb-48d4-b85d-0718114f32ea.png">
<img width="858" alt="Screenshot 2022-05-10 at 20 22 57" src="https://user-images.githubusercontent.com/67017679/167686573-2f522db7-1e8f-413f-8967-dbe81921ac47.png">
пару проблем возникает

2022-05-11 16:19 UTC, tsinevik requested changes

2022-05-11 16:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.html
> +                    <mat-icon matSuffix>schedule</mat-icon>
И убери класс `stuff`

2022-05-11 16:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.html
> +                    <mat-icon matSuffix>schedule</mat-icon>
И при включении редактирования эти два поля не заполняются существующими значениями

2022-05-11 16:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.html
> +    <do-form-row>
Поступил запрос для всех полей добавить лейбл, т.е. нужно добавить для имени, фамилии, отчества и даты рождения

2022-05-11 16:19 UTC, tsinevik commented on src/app/modules/employee/modals/edit-info/edit-info.component.scss
> +	}
чёт какая-то фигня здесь. Выглядит как хак, который принесёт нам много боли в будущем. Я примерно глянул, у тебя с широтами, похоже, какая-то проблема, всё растягивается почему-то. Так не должно быть. Грид должен быть ограничен размером модального окна.

2022-05-14 13:50 UTC, tsinevik approved these changes

2022-05-14 13:50 UTC, merged