Do 26 new component team card
LT-Students/DigitalOffice-frontend pull request #41
Opened 2020-09-21 14:26 UTC by xomnsn

1. Создала карточку команды из окна создания нового проекта. Для тестовой логики в карточке добавила родительский компонент ![блока с карточками](https://user-images.githubusercontent.com/49750021/93778119-35d3f580-fc2e-11ea-91e1-b5e3c56e4572.JPG).
Карточка получает все данные инпутом от родителя. В родителе тестовый объект с данными.
Добавление нового человека в команду вызывает метод-заглушку, чтобы показать как будет выглядеть визуально.
Вместо картинок профиля заглушка.
2. Добавила переопределяющие стили для круглой кнопки с иконкой из материала.

2020-09-21 17:00 UTC, kikichik requested changes

2020-09-21 17:00 UTC, kikichik commented on src/app/modules/admin/components/team-card/team-card.component.ts
> +    profilePic: string;
переименовать

```suggestion
    profileImgSrc: string;
```

2020-09-21 17:00 UTC, kikichik commented on src/app/modules/admin/components/team-cards/team-cards.component.html
> +</div>
Объединить всё в один компонент. Компонент не такой большой, чтобы разбивать его на 2.
```suggestion
<div class="team-cards">
  <ng-container
    *ngFor="let teamCard of teamCards"
  >
  /* твой код из team-card */
  </ng-container>
</div>
```

2020-09-21 17:00 UTC, kikichik commented on src/app/modules/admin/components/team-cards/team-cards.component.ts
> +  teamName: string;
Переименовать параметр, т.к итак понятно, что речь идет об имени команды
```suggestion
export interface TeamCard {
  name: string;
```

2020-09-21 17:00 UTC, kikichik commented on src/app/modules/admin/components/team-card/team-card.component.ts
> +      }
Здесь можно уменьшить количество кода , используя метод filter массивов
https://learn.javascript.ru/array-iteration#filter
```suggestion
    const levels = {
    junior: this.members.filter((member)=> условие проверки и т.д.
    };
```

2020-09-21 17:00 UTC, kikichik commented on src/app/modules/admin/components/team-card/team-card.component.html
> +          <do-profile-image *ngIf="member.profilePic; else iconDummy"></do-profile-image>
Добавить инжектирование profileImageSrc в do-profile-image

2020-09-21 17:00 UTC, kikichik commented on src/app/modules/admin/components/team-card/team-card.component.html
>    <div class="team-card__team-members">
В классах ` team-card__level-labels`, `team-card__header` нужно использовать наши стили и классы для текста (погляди, как это делается в других компонентах

2020-09-21 17:00 UTC, kikichik commented on src/app/modules/admin/components/new-project/new-project.component.html
> +<app-team-cards></app-team-cards>
Изменить название селектора (app-team... -> do-team... )

2020-09-21 17:00 UTC, kikichik commented on src/app/modules/admin/components/team-card/team-card.component.scss
> +    text-transform: capitalize;
Из css можно убрать.
для этого можно использовать другую фичу angular - pipe:
https://angular.io/api/common/TitleCasePipe

2020-09-21 17:01 UTC, kikichik commented
@xomnsn можно править

2020-09-23 18:18 UTC, xomnsn commented
@kikichik поправила

2020-09-27 18:50 UTC, kikichik requested changes

2020-09-27 18:50 UTC, kikichik commented on src/app/modules/admin/components/team-cards/team-cards.component.ts
> +    return levelsStr;
Попробуй избавиться от цикла и проделать всё это при помощи функции map и join
Тебе даже не понадобится вводить startDelimiter и делать проверку в цикле. + Всё решение будет в одну строку

2020-09-29 17:13 UTC, Debxit requested changes

2020-10-01 10:50 UTC, Debxit requested changes
совсем маленькие комменты

2020-10-01 10:50 UTC, Debxit commented on src/app/modules/admin/components/new-project/new-project.component.html
> +  <ng-container *ngFor="let team of teams">
ng-container тут избыточен
так
`    <do-team-card *ngFor="let team of teams" [teamCard]="team" ></do-team-card>`
тоже работает

2020-10-01 10:50 UTC, Debxit commented on src/app/modules/admin/components/new-project/new-project.component.ts
> +  teams = teamCards;
не хватает модификатора видимости и типа, хотя соответствующий интерфейс у тебя есть=)

2020-10-01 10:50 UTC, Debxit commented on src/app/modules/admin/components/team-cards/team-card.component.ts
> +  @Input() teamCard;
тип

2020-10-01 10:50 UTC, Debxit commented on src/app/modules/admin/components/team-cards/team-card.component.ts
> +  ngOnInit() {
Если OnInit не нужен, то можно просто убрать его и определение имплементации тоже

2020-10-01 10:50 UTC, Debxit commented on src/app/modules/admin/components/team-cards/team-card.component.ts
> +  public addMember(members) {
void

2020-10-05 18:09 UTC, Debxit submitted a review, later dismissed

2020-10-05 18:32 UTC, merged