Created members-board component.
LT-Students/DigitalOffice-frontend pull request #43
Opened 2020-09-22 07:47 UTC by aatroshcenko

Created members-board component.
Created search component.
Added containers styles.

2020-09-22 09:36 UTC, Debxit requested changes

2020-09-22 09:36 UTC, Debxit commented on src/app/interfaces/member.interface.ts
> +export interface IMember{
насколько я помню код стайл от ангуляра, не нужно добавлять I для интерфейсов

2020-09-22 09:36 UTC, Debxit commented on src/stylesheets/layouts/_containers.scss
> +.flex-container{
а нам действительно это нужно?
Это дело вкуса, конечно. Но мне кажется, что такой подход утяжеляет чтение html. 
Я предпочитаю прописывать это в стилях конкретного контейнера

2020-09-22 09:36 UTC, Debxit commented on src/app/modules/shared/search/search.component.html
> +    <button mat-icon-button
Что по поводу обработки enter?

2020-09-22 19:24 UTC, aatroshcenko commented on src/app/interfaces/member.interface.ts
> +export interface IMember{
Да, в код стайле для Typescript об этом сказано, уберал.

2020-09-22 19:42 UTC, aatroshcenko commented on src/stylesheets/layouts/_containers.scss
> +.flex-container{
Дело в том, что мы практически везде используем этот display: flex.
Вот насчет чтения html: вот, допустим, 'members-board' класс там может быть display: grid и block и еще чего , нежели 'member-board flex-container flex-container_direction_column' тут нам не надо заглядывать в стили даже.
Возможно, название не очень удачное. Вообще нам Никита скидывал гайд по css и там был абзац посвященный адаптивной верстке, я хотел по началу его взять, но там ,видимо, из проекта его файлы. 
![image](https://user-images.githubusercontent.com/42975691/93929533-af4e0f80-fd24-11ea-89ae-7fc47bebb930.png)

2020-09-22 19:50 UTC, aatroshcenko commented on src/app/modules/shared/search/search.component.html
> +    <button mat-icon-button
А там автоматические на enter нажимается кнопка, так что отдельной обработки не надо

2020-10-05 18:07 UTC, Debxit approved these changes

2020-10-05 18:07 UTC, merged