DO-31 Добавить раздел "Команда" в компонент "Новый проект"
LT-Students/DigitalOffice-frontend pull request #46
Opened 2020-10-20 18:06 UTC by xomnsn

Добавлена вёрстка раздела "Команда" в компонент "Новый проект", карточки команды и список объединены с помощью tabs из angulat material. Ещё поправлен паддинг wrapper'а у всего приложения.

2020-10-21 17:01 UTC, AlexLevus requested changes

2020-10-23 12:11 UTC, xomnsn commented on src/app/modules/admin/components/dashboard/dashboard.component.html
> +      <img
В angular.json "sourceRoot": "src", "prefix": "app",  "assets": ["src/favicon.ico", "src/assets"], но в этом компоненте идея только путь "../assets/images/fon.png" видит. Такое впечатление, что корень это app... Может из-за вот этого prohibited property не работает (картинка) или так и должно быть..?
![image](https://user-images.githubusercontent.com/49750021/97001811-aded4e00-1541-11eb-8ff9-34cc4e4b9a9c.png)

2020-10-23 12:16 UTC, xomnsn commented on src/app/modules/admin/components/new-project/new-project.component.html
> +    <h3 class="team__section-title h3 text_bold text_dark_1">Команда</h3>
А ничего страшного, что тег будет правильный по иерархии, а стиль для h3? или поправить стили в stylesheets/base/fonts чтобы они нейтрально назывались?

2020-10-23 12:42 UTC, xomnsn commented on src/app/modules/admin/components/new-project/new-project.component.html
> +    <h3 class="team__section-title h3 text_bold text_dark_1">Команда</h3>
nvm, всё работает, просто идее не нравится почему-то

2020-10-23 12:44 UTC, xomnsn commented on src/app/modules/admin/components/dashboard/dashboard.component.html
> +      <img
nvm, всё работает, просто идее не нравится почему-то

2020-10-23 13:46 UTC, AlexLevus commented on src/app/modules/admin/components/new-project/new-project.component.html
> +            </svg>
Хотя знаешь, сделай лучше так, чтобы универсально размеры можно было бы задавать:

`<img src="assets/svg/plus.svg" height="26" width="26">
`

2020-10-23 13:50 UTC, AlexLevus commented on src/app/modules/admin/components/dashboard/dashboard.component.html
> +      <img
Точно не скажу, у меня в WebStorm все нормально
А если так? "/assets/images/fon.png"

2020-10-23 13:54 UTC, AlexLevus commented on src/app/modules/admin/components/new-project/new-project.component.html
> +    <h3 class="team__section-title h3 text_bold text_dark_1">Команда</h3>
Это выглядит, конечно, нелогично. Наверное, лучше уточнить у Оли
Вообще, я не фанат использования такого нейминга как у bootstrap

2020-10-27 17:11 UTC, AlexLevus approved these changes

2020-10-27 17:37 UTC, merged