'do 27 new member'
LT-Students/DigitalOffice-frontend pull request #47
Opened 2020-10-21 19:59 UTC by AnastassiaVarabei

2020-10-22 16:10 UTC, AlexLevus requested changes

2020-10-22 16:10 UTC, AlexLevus commented on src/app/modules/admin/components/new-member/new-member.component.html
> +            </mat-option>
У каждого сотрудника ведь свой набор специализации, поэтому возьми их из employee.specializations

2020-10-22 16:10 UTC, AlexLevus commented on src/app/modules/admin/components/new-member/new-member.component.html
> +      <p class="regular_text text_color_gray">2 проекта</p>
А это из employee.projectsCount

2020-10-22 16:10 UTC, AlexLevus commented on src/app/modules/admin/components/new-member/new-member.component.scss
> +}
По стилям пока писать не буду. Есть расширение PixelParallel, оно позволяет сделать так:

![Скриншот 22-10-2020 174424](https://user-images.githubusercontent.com/33965367/96899218-51365880-1499-11eb-87cb-b2b747090ac5.png)

Идеального PixelPerfect не надо, но что-то похожее на то, что в макете должно быть 100%

2020-10-27 10:54 UTC, AnastassiaVarabei commented on src/app/app-routing.module.ts
> +          { path: 'members-board', component: MembersBoardComponent }
Переименовала

2020-10-27 11:15 UTC, AnastassiaVarabei commented on src/app/modules/admin/admin.module.ts
> +    MatCheckboxModule
Прописала через AppMaterialModule

2020-10-27 11:19 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/members-board/members-board.component.html
> +      <div *ngIf="this.members.length == 0"
Изменила на строгое сравнение

2020-10-28 07:50 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/members-board/new-members.ts
> +];
Исправила

2020-10-28 07:50 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-member/new-member.component.html
> +            </mat-option>
Исправила

2020-10-28 07:50 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-member/new-member.component.html
> +      <p class="regular_text text_color_gray">2 проекта</p>
Исправила

2020-10-29 08:55 UTC, Debxit requested changes
Еще заметила разный border-radius в разных состояния чекбокса - надо поправить
![image](https://user-images.githubusercontent.com/6964972/97546476-8bde4a80-19dd-11eb-8261-4ff86ff0e2d0.png)

2020-10-29 08:55 UTC, Debxit commented on libs/api/src/lib/auth-service/model/authenticationResponse.ts
>      token?: string;
А почему все эти файлы изменены в твоем ПРе? По идее в твоем ПРе должны отображаться только измененные тобой файлы.

2020-10-29 08:55 UTC, Debxit commented on src/app/modules/admin/components/new-member/new-member.component.scss
> +    //width: 118px;
я думаю, здесь нужно задать минимальную ширину, чтобы вот так не съезжали проекты в компоненте
![image](https://user-images.githubusercontent.com/6964972/97546276-44f05500-19dd-11eb-8cff-75a83c6ed911.png)

2020-10-29 15:17 UTC, AnastassiaVarabei commented on libs/api/src/lib/auth-service/model/authenticationResponse.ts
>      token?: string;
Вернула как было.

2020-10-29 15:50 UTC, AnastassiaVarabei commented on libs/api/src/lib/auth-service/model/authenticationResponse.ts
>      token?: string;
![image](https://user-images.githubusercontent.com/61653983/97598113-a0d7cf80-1a17-11eb-8aa6-e397c797525b.png)
Исправила

2020-10-29 16:13 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-member/new-member.component.scss
> +    //width: 118px;
Оставила фиксированную ширину.

2020-10-30 09:16 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-member/new-member.component.scss
> +    //width: 118px;
ширину исправила на %

2020-11-01 09:58 UTC, AlexLevus submitted a review, later dismissed

2020-11-05 10:02 UTC, closed without merging