added api for new-employee component
LT-Students/DigitalOffice-frontend pull request #52
Opened 2020-11-06 20:59 UTC by MariyaSin

2020-11-25 07:05 UTC, Debxit requested changes

2020-11-25 07:05 UTC, Debxit commented on src/app/modules/admin/components/new-employee/new-employee.component.html
> +              <mat-error *ngIf="userForm.controls.login.hasError('required')">
см коммент по поводу текста ошибки. Также тут должен быть добавлены еще mat-error с соответствующими текстами, на тот случай если длина логина будет меньше или больше необходимой длины. (У тебя есть для этой проверки валидаторы, значит должно быть и сообщение)

2020-11-25 07:05 UTC, Debxit commented on src/app/modules/admin/components/new-employee/new-employee.component.html
> +                The password is invalid
Тоже самое про текст ошибки

2020-11-25 07:05 UTC, Debxit commented on src/app/modules/admin/components/new-employee/new-employee.component.ts
> +import { HttpErrorResponse } from '@angular/common/http';
Это общая библиотека, должна быть в верхней группе

2020-11-25 07:05 UTC, Debxit commented on src/app/modules/admin/components/new-employee/new-employee.component.ts
> +  user: User;
модификатор видимости?

2020-11-25 07:05 UTC, Debxit commented on src/app/modules/admin/components/new-employee/new-employee.component.ts
> +    public snackBar: MatSnackBar
Вызывается ли этот севис из html? Если нет, то он должен быть private

2020-11-25 07:05 UTC, Debxit commented on src/app/modules/admin/components/new-employee/new-employee.component.ts
> +          Validators.minLength(1),
Я думаю валидатор на минимальную длину можно убрать, т.к. у тебя уже есть required, т.е. хотя бы один символ юзер введет

2020-11-25 22:56 UTC, MariyaSin commented on src/app/modules/admin/components/new-employee/new-employee.component.html
> +                    imgURL
у меня шторм верии 2020.1, если я смогу подключить, то было бы здорово, если ты мне скинешь свои настройки

2020-11-26 14:01 UTC, Debxit requested changes

2020-11-26 14:01 UTC, Debxit commented on src/app/modules/admin/components/new-employee/new-employee.component.html
> +                The login is to short
Надо поправить "The login is to short" на "The login is too short"

2020-11-26 14:01 UTC, Debxit commented on src/app/modules/admin/components/new-employee/new-employee.component.html
> +                The middle name is to long
too

2020-11-26 14:01 UTC, Debxit commented on src/app/modules/admin/components/new-employee/new-employee.component.html
> +                The login is to long
too

2020-11-26 14:01 UTC, Debxit commented on src/app/modules/admin/components/new-employee/new-employee.component.html
> +                The first name is to long
too

2020-11-26 14:01 UTC, Debxit commented on src/app/modules/admin/components/new-employee/new-employee.component.html
> +                The last name is to long
too

2020-12-01 19:15 UTC, Debxit approved these changes

2020-12-01 19:17 UTC, merged