Do 34 style buttons
LT-Students/DigitalOffice-frontend pull request #55
Opened 2020-11-26 21:52 UTC by AnastassiaVarabei

2020-11-28 15:08 UTC, Debxit requested changes

2020-11-28 15:08 UTC, Debxit commented on src/stylesheets/material/_button.scss
> +.mat-stroked-button {
нужно переопределить стили, тут, скорее всего не хватит вложенности.
Условно, если я где-то использовала 
` <button mat-stroked-button color="primary">Primary</button>`
, то но выходе получаю такой html 
`<button _ngcontent-xtc-c155="" mat-stroked-button="" color="primary" type="submit" class="mat-focus-indicator mat-stroked-button mat-button-base mat-primary mat-button-disabled" ng-reflect-color="primary" ng-reflect-disabled="true" disabled="true"><span class="mat-button-wrapper"><span _ngcontent-xtc-c155="" class="regular_text regular_text_light_1">Создать сотрудника</span></span><span matripple="" class="mat-ripple mat-button-ripple" ng-reflect-disabled="true" ng-reflect-centered="false" ng-reflect-trigger="[object HTMLButtonElement]"></span><span class="mat-button-focus-overlay"></span></button>`

Тут много классов в итоге навешивается и тебе надо посмотреть какой комбинацией классов в стилях, ты сможешь переопределить дефолтные стили.

Это касается и mat-flat-button

2020-12-01 20:29 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-members-board/new-members-board.component.scss
> +@import 'material/button';
Оставила только в style.scss

2020-12-01 21:48 UTC, AnastassiaVarabei commented on src/stylesheets/material/_button.scss
> +    width: 125px;
Исправила. Для черной кнопки применила материаловский класс .mat-raised-button

2020-12-01 22:02 UTC, AnastassiaVarabei commented on src/stylesheets/material/_button.scss
> +.mat-stroked-button {
стили переопределила

2020-12-01 22:03 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-members-board/new-members-board.component.html
> +        class="mat-flat-button-accent mat-flat-button-accent_medium regular_text"
убрала классы

2020-12-01 22:03 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-members-board/new-members-board.component.html
> +      <button
классов нет. Только то, что использует материал

2020-12-02 18:15 UTC, AlexLevus requested changes

2020-12-02 18:15 UTC, AlexLevus commented on src/stylesheets/material/_button.scss
> +  font-family: Gill Sans, sans-serif;
Такого шрифта нет

Есть такой $regular_font: 'GillSansWGL';

2020-12-02 18:15 UTC, AlexLevus commented on src/stylesheets/material/_button.scss
> +  font-family: Gill Sans, sans-serif;
Такого шрифта нет

Есть такой $regular_font: 'GillSansWGL';

2020-12-02 18:15 UTC, AlexLevus commented on src/stylesheets/material/_button.scss
> +}
Переиспользование кода всегда должно смущать

Есть принцип DRY - Dont Repeat Yourself

В твоем случае переиспользования можно избежать
Например, вынести общие стили под общий селектор. Или просто через перечисление, например:
`
selector1, selector2, selector3 {
   styles
}
`

2020-12-02 18:22 UTC, AlexLevus requested changes

2020-12-02 18:22 UTC, AlexLevus commented on src/stylesheets/material/_button.scss
> +button.mat-button-disabled {
Кроме disabled есть еще несколько состояний

Например, hover, active, focus

2020-12-03 18:38 UTC, AnastassiaVarabei commented on src/stylesheets/material/_button.scss
> +  font-family: Gill Sans, sans-serif;
Шрифт  заменила на font-family: GillSansWGL

2020-12-03 18:38 UTC, AnastassiaVarabei commented on src/stylesheets/material/_button.scss
> +  font-family: Gill Sans, sans-serif;
Шрифт заменила на font-family: GillSansWGL

2020-12-03 18:55 UTC, AnastassiaVarabei commented on src/stylesheets/material/_button.scss
> +}
Общие стили объединила и вынесла под общие селекторы

2020-12-07 15:26 UTC, AlexLevus approved these changes

2020-12-07 15:28 UTC, merged