Change bootstrap date picker to material
LT-Students/DigitalOffice-frontend pull request #56
Opened 2020-12-01 09:45 UTC by xomnsn

Исправила комментарии с прошлого пр и нормально залила этот (только с моими коммитами). Убрала зависимость от бутсраповских дат и прошлого календаря вообще.

2020-12-02 20:01 UTC, Debxit requested changes
Бегло посмотрела сегодня. По логике еще раз завтра гляну на свежую голову.

2020-12-02 20:34 UTC, xomnsn commented on src/app/modules/user/components/attendance/attendance.service.ts
> +    this.timePeriod$.next(this.currentTimePeriod);
Я её использовала, чтобы когда выбор дат в календаре не завершён, а календарь закрыт, или ошибка в выборе периода (ошибку я потом закрыла до её появления) всё возвращалось к предыдущему значению, но я так и не нашла как это сделать и нужно ли, пока не понимаю, так что в принципе она не нужна. countPlannedHours ваще не работает сейчас. Спасибо, всё почитаю

2020-12-02 20:37 UTC, xomnsn commented on src/app/modules/user/components/attendance/attendance.service.ts
> +  private checkTimePeriod(
Оно потому что было про проверку) Но да, поменяю, там вообще пока с неймингом беда, где-то time, где-то date, где-то from/to, где-то start/end, я пока просто на это не распылялась и называла по аналогии с тем, как раньше было, хорошо бы там всё поправить и единообразно назвать, конечно

2020-12-16 07:49 UTC, Debxit requested changes

2020-12-16 07:49 UTC, Debxit commented on src/app/app-routing.module.ts
> +        // canActivate: [AuthGuard, AdminGuard]
вот это надо будет вернуть

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/add-hours/add-hours.component.html
> +    class="add-hours__form regular_text"
по БЭМу тут можно было рядом проставить класс form или что-то еще и уже ему добавлять элементы, т.к. форма - это отдельный блок, а у тебя получается, что вся  страница один большой блок

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/add-hours/add-hours.component.html
> +      class="add-hours__label add-hours__label_for_description"
меня смущают такие длиннющие классы) Во-первых, модификатор пишется через _ и все, дальше уже _ не должно быть, т.е. for-description. Во-вторых, это один и тот же лейбл, но с разным цветом/размером и т.д? Если нет, то модификатор тут не нужен, как мне кажется.

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/add-hours/add-hours.component.html
> +      class="mat-flat-button mat-flat-button_style_black add-hours__submit-btn"
и тут style явно лишний)

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/add-hours/add-hours.component.ts
> +    return +this.attendanceService.countRecommendedTime(currentDatePeriod, 24)
лучше использовать явное преобразование Number(), так код выглядит чище

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/add-hours/add-hours.component.ts
> +    return this.projects.map((project: IProject) => project.name);
Возможно, в будущем нам будет приходить массив проектов и там будут айдишники, которые надо будет отправлять при проставлении часов. Поэтому лучше в ngFor передавать просто массив проектов, а не их имен. И там уже в value проставлять project.id а в названии project.name.

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/add-hours/add-hours.component.ts
> +    return this.projects.map((project: IProject) => project.name);
А этот метод тогда убрать

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/add-hours/add-hours.component.ts
> +    const project_id = +this.addHoursForm.get('project').value;
Number()

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/add-hours/add-hours.component.ts
> +        hours: +this.addHoursForm.get('time.hours').value,
the same

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/add-hours/add-hours.component.ts
> +    console.log(minutes?.errors);
delete

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/add-hours/add-hours.component.ts
> +    if (minutes.errors?.['max']) {
можно воспользоваться методом minutes.hasError('max')

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/add-hours/add-hours.component.ts
> +    this.onDestroy.next(null);
т.к. переменная onDestory subject ее лучше переименовать в onDestroy$

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/add-hours/add-hours.validators.ts
> +    +control.value < countMaxPossibleHours()
Number()

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/attendance/attendance.service.ts
> +      return { startDate: this.tempStartDate, endDate: datePeriod.endDate };
не поняла зачем здесь проставляется tempStartDate. Эта переменная где-то еще инициализиуется? Или только в блоке выше?

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/attendance/attendance.service.ts
> +  public normalizeTime(time: any): String {
стандартные типы пишутся с маленькой буквы = string

2020-12-16 07:49 UTC, Debxit commented on src/app/modules/user/components/date-desc/date-desc.component.html
> +          *ngIf="
форматирование!!)))

2020-12-16 11:18 UTC, xomnsn commented on src/app/modules/user/components/add-hours/add-hours.component.html
> +      class="add-hours__label add-hours__label_for_description"
Это модификатор ключ_значение, по [бэму](https://ru.bem.info/methodology/faq/#%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-%D0%B1%D1%83%D0%BB%D0%B5%D0%B2%D1%8B%D0%B9-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80-%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0--%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80-%D0%BA%D0%BB%D1%8E%D1%87-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5). если форму выделить как отдельный блок будут покороче) получается элемент label для всех лейблов (там марджин общий), а _for_description/task/project - для каждого отдельного лейбла модификаторы типа ключ_значение, в макете у всех разные отступы.

2020-12-16 11:42 UTC, xomnsn commented on src/app/modules/user/components/attendance/attendance.service.ts
> +      return { startDate: this.tempStartDate, endDate: datePeriod.endDate };
Вообще она для того, чтобы помнить дату начала периода, когда выбирается конец периода. В календаре эмитится не период, а дата из какого-то из инпутов начала/конца. А из недели сверху выбирается сразу один день как период. Получается нужно, чтобы onDatePeriodChange() работала и с полувыбранным периодом, и с полным. А tempStartDate ставится как начало периода, когда приходит период типа {начало: null, конец: дата}. То есть когда инпут конца периода в календаре эмитит дату. Но вообще я сама такой период посылаю из компонента (картинка), так что наверное tempStartDate можно перенести в файл компонента, чтобы в методе сервиса периоды типа {начало: null, конец: дата} не приходили.
![image](https://user-images.githubusercontent.com/49750021/102343919-38838400-3fac-11eb-8007-28069318c41f.png)

2020-12-16 18:49 UTC, merged