changed svg in auth.component and changed style for login and forgot-…
LT-Students/DigitalOffice-frontend pull request #58
Opened 2020-12-10 21:50 UTC by AnastassiaVarabei

…password: text, color ...

2020-12-11 09:13 UTC, AlexLevus requested changes

2020-12-11 09:13 UTC, AlexLevus commented on src/app/modules/auth/components/auth/auth.component.html
> +    <img id="wave1" src="../../../../../assets/svg/wave2.svg" />
Путь до svg можно сократить assets/svg/wave2.svg"

2020-12-11 09:13 UTC, AlexLevus commented on src/app/modules/auth/components/auth/auth.component.scss
> +      //opacity: 0.24;
Если не используется, то убрать

2020-12-11 09:13 UTC, AlexLevus commented on src/app/modules/auth/components/auth/auth.component.html
> +    <img id="wave1" src="../../../../../assets/svg/wave1.svg" />
Если id нигде не используются, то убрать

2020-12-11 09:13 UTC, AlexLevus commented on src/app/modules/auth/components/forgot-password/forgot-password.component.html
> +  <!--  </div>-->
Разве этот текст не нужен?
Поменяй просто на русский язык

2020-12-11 09:13 UTC, AlexLevus commented on src/app/modules/auth/components/login/login.component.html
> +    <small *ngIf="!isEmailInputValid()"> </small>
Почему убрала текст? Он нужен
Сделай еще, чтобы при ошибке  все сообщения показывались в столбик

2020-12-11 16:10 UTC, AnastassiaVarabei commented on src/app/modules/auth/components/forgot-password/forgot-password.component.html
> +  <!--  </div>-->
Вернула, текст изменила на русский. Ошибка будет после input

2020-12-11 16:12 UTC, AnastassiaVarabei commented on src/app/modules/auth/components/login/login.component.html
> +    <small *ngIf="!isEmailInputValid()"> </small>
Исправила

2020-12-11 18:00 UTC, AnastassiaVarabei commented on src/app/modules/auth/components/auth/auth.component.html
> +    <img id="wave1" src="../../../../../assets/svg/wave1.svg" />
Убрала)

2020-12-14 16:14 UTC, AlexLevus approved these changes

2020-12-14 16:14 UTC, merged