added form with id='addition'
LT-Students/DigitalOffice-frontend pull request #59
Opened 2021-01-15 19:33 UTC by AnastassiaVarabei

2021-02-07 12:01 UTC, AlexLevus requested changes

2021-02-07 12:03 UTC, AlexLevus requested changes

2021-02-07 12:03 UTC, AlexLevus commented on src/app/modules/admin/components/new-project/new-project.component.html
> +          >Просмотр проекта только для членов команды</mat-checkbox
Привязать контрол для profileForm

2021-02-13 19:06 UTC, AnastassiaVarabei commented on src/app/guards/admin.guard.ts
> +// }
убрала)

2021-02-13 19:06 UTC, AnastassiaVarabei commented on src/app/guards/auth.guard.ts
> +// }
убрала)

2021-02-13 19:22 UTC, AnastassiaVarabei commented on src/assets/svg/loading.svg
> +<svg width="49" height="32" viewBox="0 0 49 32" fill="none" xmlns="http://www.w3.org/2000/svg">
переименовала

2021-02-13 19:24 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-project/new-project.component.scss
> +  &__loading {
переименовала

2021-02-13 19:25 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-project/new-project.component.html
> +          class=".border-accent_color_bright"
точку убрала

2021-02-13 19:25 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-project/new-project.component.html
> +        class=".border-accent_color_bright"
точку убрала

2021-02-13 19:27 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-project/new-project.component.html
> +      <div class="content-container__section-secret">
переименовала

2021-02-13 19:27 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-project/new-project.component.scss
> +    &-secret {
переименовала

2021-02-13 19:28 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-project/new-project.component.html
> +<!--<div class="content-container bg-white">-->
убрала закомментированный код)

2021-02-13 19:45 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-project/new-project.component.html
> +            formControlName="addition"
Добавила и переименовала

2021-02-13 19:59 UTC, AnastassiaVarabei commented on src/app/modules/admin/components/new-project/new-project.component.html
> +          >Просмотр проекта только для членов команды</mat-checkbox
привязала

2021-02-16 18:47 UTC, AlexLevus approved these changes

2021-02-16 18:48 UTC, merged