Do upload
LT-Students/DigitalOffice-frontend pull request #63
Opened 2021-02-21 21:29 UTC by AnastassiaVarabei

2021-02-22 18:28 UTC, AlexLevus requested changes

2021-02-22 18:28 UTC, AlexLevus commented on src/app/modules/admin/admin.module.ts
> +import { UploadComponent } from './components/upload/upload.component';
Думаю, это все надо определить в shared module
 + в shared создай, пожалуйста, папки component и directive, соответственно, компоненты в одну, директивы в другую

2021-02-25 15:26 UTC, AnastassiaVarabei commented on src/app/modules/admin/admin.module.ts
> +import { UploadComponent } from './components/upload/upload.component';
Пока создала только пустые папки.

2021-02-26 08:32 UTC, AlexLevus approved these changes

2021-02-26 08:32 UTC, merged