Employee info component
LT-Students/DigitalOffice-frontend pull request #70
Opened 2021-03-24 15:44 UTC by tsinevik

1. Сверстал блок общей информации о сотруднике
2. Сверстал форму для редактирования по ролям
3. Добавил простой функционал для редактирования информации сотрудника

2021-03-25 14:53 UTC, NikGurev requested changes

2021-03-25 14:53 UTC, NikGurev commented on src/app/shared/component/employee-info/employee-info.component.html
> +                svgIcon="question-mark"
`svgIcon="question-mark"` может не сработать, лучше добавь внутрь тега

2021-03-25 14:53 UTC, NikGurev commented on src/app/shared/component/employee-info/employee-info.component.ts
> +    photo: 'assets/images/employee-photo.png',
использовать интерфейс User 
https://app.swaggerhub.com/apis/LT.DigitalOffice.1/UserService/1.2.0#/UserStatus

2021-03-25 14:53 UTC, NikGurev commented on src/app/shared/component/employee-info/employee-info.component.ts
> +  }
в текущей реализации сервисов поле User имеет свойство isAdmin, так что свойство role излишне

2021-03-25 14:53 UTC, NikGurev commented on src/app/shared/component/employee-page/employee-page.component.html
> +</div>
это можно убрать, так как я еще не все доделал

2021-03-25 14:53 UTC, NikGurev commented on src/app/shared/component/employee-info/employee-info.component.ts
> +  }
метод нужно будет переработать. Думаю, все же будет сравнение не по роли, а по ID

2021-03-25 14:53 UTC, NikGurev commented
также надо поправить конфликты

2021-03-29 11:16 UTC, NikGurev requested changes

2021-03-29 11:16 UTC, NikGurev commented on src/app/shared/component/employee-info/employee-info.component.ts
> +    this.employeeInfoForm.patchValue({ workingRate: rate });
думаю, здесь нужно в disable ставить кнопки "+" и "-" при достижении максимальных значений. Это избавит нас от конструкции if else
p.s. синтаксис такой:
Допускается писать `if () { block } `, если одно действие
```
if (condition) {
   block;
} else {
 block;
}
```

2021-03-29 11:16 UTC, NikGurev commented on src/app/shared/component/datepicker/datepicker.component.scss
> +}
попробуй реализовать через сокращенный синтаксис &__type
https://sass-scss.ru/documentation/sassscript/&_v_sassscript/

2021-03-29 11:16 UTC, NikGurev commented on src/app/shared/component/employee-info/employee-info.component.ts
>      middleName: 'Анатольевна',
по-хорошему, свойства класса инициализируются в конструкторе, а  до конструктора просто объявляется свойство и его тип. Погляди как я делал в своем компоненте

2021-03-29 18:25 UTC, AlexLevus requested changes

2021-03-29 18:25 UTC, AlexLevus commented on src/app/shared/component/input/input.component.ts
> +  @Input() isAdmin = true;
Этого не должно быть внутри, твой компонент должен быть переиспользуемым, тут ты сильно завязываешься на текущий контекст своей задачи

Информация о доступности редактирования должна приходить через isEdit

2021-03-29 18:25 UTC, AlexLevus commented on src/app/shared/component/select/select.component.ts
> +  @Input() isAdmin = true;
Этого не должно быть внутри, твой компонент должен быть переиспользуемым, тут ты сильно завязываешься на текущий контекст своей задачи

Информация о доступности редактирования должна приходить через isEdit

2021-03-29 18:25 UTC, AlexLevus commented on src/app/shared/component/employee-info/employee-info.component.ts
> +    return this.employee.isAdmin || this.isOwner;
Справедливо не для всех полей

2021-03-29 18:25 UTC, AlexLevus commented on src/app/shared/component/employee-info/employee-info.component.ts
> +  @Input() pageId = '0';
Бери pageId из url строки, для это придется немного переделать роутинг (path: 'employee/:id')

2021-03-29 18:25 UTC, AlexLevus commented on src/app/shared/component/employee-info/employee-info.component.ts
> +    this.toggleEditMode();
Думаю, не стоит для такой "логики" создавать отдельный метод, лучше просто сразу (reset)="toggleEditMode()"

2021-03-29 18:25 UTC, AlexLevus commented on src/app/shared/component/employee-info/employee-info.component.ts
> +  ngOnInit(): void {
Лучше сразу инициализировать в месте объявления формы

2021-03-29 18:25 UTC, AlexLevus commented on src/app/shared/component/input/input.component.html
> +  <div>{{ value }}</div>
Можно просто control.value

2021-03-29 18:25 UTC, AlexLevus commented on src/app/shared/component/input/input.component.ts
> +  @Input() value: string | number = '';
Можно достать через control.value

2021-03-29 18:25 UTC, AlexLevus commented on src/app/shared/component/datepicker/datepicker.component.ts
> +  @Input() value: Date;
Можно достать через control.value

2021-03-29 18:25 UTC, AlexLevus commented on src/app/shared/component/select/select.component.ts
> +  @Input() value: string;
Можно достать через control.name

2021-03-29 18:25 UTC, AlexLevus commented on src/app/shared/component/employee-info/employee-info.component.ts
> +    if (!this.isEditable) this.fillForm();
If всегда через скобки

2021-03-30 09:41 UTC, NikGurev approved these changes

2021-03-30 10:07 UTC, AlexLevus requested changes
Все хорошо
Осталось доработать формат отображения дат

2021-03-30 12:53 UTC, AlexLevus approved these changes

2021-03-30 12:53 UTC, merged