Feature/employee page projects
LT-Students/DigitalOffice-frontend pull request #87
Opened 2021-04-13 10:42 UTC by tsinevik

https://trello.com/c/5HMXalok/88-страница-сотрудника-верстка-раздела-проекты

2021-04-13 17:21 UTC, AlexLevus requested changes

2021-04-13 17:21 UTC, AlexLevus commented on src/app/modules/employee/components/employee-page-projects/employee-page-projects.component.ts
> +    this.pluralForm = {
Можно вынести в функцию
Посмотри пример в new-member.component.ts

2021-04-13 17:21 UTC, AlexLevus commented on src/app/modules/employee/components/employee-page-projects/employee-page-projects.component.scss
> +    grid-template-columns: repeat(4, 1fr);
Можно, кстати, заюзать grid list в angular material, но это по желанию

2021-04-13 17:21 UTC, AlexLevus commented on src/app/modules/employee/components/employee-page-projects/employee-page-projects.component.html
> +      <h3 class="projects-table__group-title h3_light">
Если заголовок "Проекты" сверху h3, то тогда тут h4 по идее

2021-04-19 17:12 UTC, NikGurev commented on src/app/modules/employee/employee.module.ts
> +		EmployeePageProjectsComponent
можно просто projectscomponent, по аналогии с выщестоящими

2021-04-19 17:17 UTC, NikGurev commented on src/app/modules/employee/components/employee-page-projects/employee-page-projects.component.ts
> +  expanded: boolean;
что означает свойство `expanded` ? Я так понимаю, что кнопка "Подробнее" ведет на страницу проекта конкретно, а не расширяет контейнер

2021-04-19 17:18 UTC, NikGurev commented on src/app/modules/employee/components/employee-page-projects/employee-page-projects.component.ts
> +  plural: {};
использовать type `object` вместо `{}`

2021-04-19 17:21 UTC, NikGurev commented on src/app/modules/employee/components/employee-page-projects/employee-page-projects.component.html
> +      </h4>
не совсем понимаю, почему у тебя тег h4 , а класс h3_light? нелогично
используй директиву в текстовых полях

2021-04-22 14:16 UTC, merged